nolimits4web/swiper

src/idangerous.swiper.js
Missing spaces and a semicolon
=> jshint:lib errors

src/js/dom-plugins.js
Replace references to `$`with `domLib`, otherwise the jquery file will fail if jquery is in noConflict mode.
=> Fix ambiguous $ variable

component.json
Fixed issue I ran into issue while using duo. Since component.json pointed to wrong folders component and duo stopped working after the v.3.x.x update.
=> updated component.json since it wasn't pointing to any files

package.json
Make able to build swiper style via postcss-import.
https://github.com/postcss/postcss-import#usage
=> Add style directive

src/js/core.js
Another try.
Fix `roundLengths` for wrapper translate.
=> fix roundLengths for wrapper translate

package.js
TODO (@nolimits4web ):
1. create a meteor user account (you can use nolimits4web, if you want to use other name, please change 'name' attribute in package.js)
2. publish the package https://atmospherejs.com/i/publishing
3. when you update your package to a new version, please change the version in package.js and republish.
Thank you for your awesome package! It would be awesomer if you can support meteor users!
=> add support for meteor

src/js/angular.js
basically implementation of https://github.com/nolimits4web/Swiper/issues/1131
all options are supported -> if something is configured the wrong way it will only show an error in the console (and not break the whole angular app)
```javascript
(function (angular) {
var app = angular.module('mm.swiper', []);
app.directive('swiperContainer', [
'$log',
function($log) {
return {
restrict: 'C',
link: function(scope, element, attributes) {
if (typeof attributes.breakpoints === 'string') {
attributes.breakpoints = JSON.parse(attributes.breakpoints);
}
if (typeof attributes.fade === 'string') {
attributes.fade = JSON.parse(attributes.fade);
}
if (typeof attributes.cube === 'string') {
attributes.breakpoints = JSON.parse(attributes.cube);
}
if (typeof attributes.coverflow === 'string') { …
```
=> angularjs port

demos/32-slideable-menu.html
I have created a slideable menu using Swiper. I think it can be useful for the community as well. This demo can also demonstrate well that Swiper can be used in a wide range.
=> Add slideable menu demo

API.md
Just fixed the numbering and formatting on the v2 docs.
The numbered list wasn't aligning correctly and it just bugged me a little.
=> Fix formatting on v2 docs

src/js/core.js, src/js/keyboard.js
I needed to bind custom functions for custom key codes so i just emit a new event which is onKeyPress
=> Emit keyPress event at the end of keyboard control

src/js/core.js
This is to fix this issue: https://github.com/nolimits4web/Swiper/issues/2046
=> do not resize when slides are hidden

src/js/core.js
Add event emitting before changing the slide.
=> Add before change slide event

src/components/core/events/onTouchStart.js
subject line describes all that's needed to know about this PR...
=> fix noSwipingClass functionality

src/components/core/core-class.js
=> Fix prevented click event

src/components/core/breakpoints/getBreakpoint.js
=> Updated sorting for chrome 62. Fixes #2345

src/components/history/history.js
Fixes https://github.com/nolimits4web/Swiper/issues/2353
=> implement missing destroy method for swiper.history

CHANGELOG.md
"incoroporated" fixed to "incorporated"
=> small typo fixed

src/components/core/check-overflow/index.js, src/components/core/core-class.js, src/components/core/defaults.js, src/components/core/update/updateSlides.js, src/components/navigation/navigation.js, src/components/navigation/navigation.less, src/components/pagination/pagination.js, src/components/pagination/pagination.less, src/components/scrollbar/scrollbar.js, src/components/scrollbar/scrollbar.less
Disable swiper and hide navigation when container not overflow
Слайдер будет отключаться и скрывать навигацию когда слайды не выходят за пределы контейнера.
=> add parameter watchOverflow

Architecture
The swiper documentation is very good at defining attributes and functions.  But it does not tell much about the architecture.  One is not able to reason about Swiper.  So I decided to write this architecture document.
Always follow the [contribution guidelines](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md) when submitting a pull request.
=> New Architecture document

src/components/core/check-overflow/index.js, src/components/core/events/onResize.js
some click events did not work with checkOverflow=true
=> checkOverflow: click problem && add lock events

src/components/core/grab-cursor/setGrabCursor.js, src/components/core/grab-cursor/unsetGrabCursor.js
Prevent apply grab cursor when swiper is locked.
=> Prevent apply grab cursor when swiper is locked

package.json
Required for packagist.org submission and installation via composer.
=> composer.json

src/components/mousewheel/mousewheel.js
``swiper.stopAutoplay()`` should be replaced by ``swiper.autoplay.stop()``
=> :bug: Fix Bug: swiper.stopAutoplay() => swiper.autoplay.stop()

src/components/core/loop/loopDestroy.js
=> Remove blank slides on loop destroy

src/components/parallax/parallax.js
=> Fix parallax still being applied when disabled

src/components/a11y/a11y.scss, src/components/core/core.scss, src/components/effect-coverflow/effect-coverflow.scss, src/components/effect-cube/effect-cube.scss, src/components/effect-fade/effect-fade.scss, src/components/effect-flip/effect-flip.scss, src/components/lazy/lazy.scss, src/components/navigation/navigation.scss, src/components/pagination/pagination.scss, src/components/scrollbar/scrollbar.scss, src/components/thumbs/thumbs.scss, src/components/zoom/zoom.scss, src/scss/functions.scss, src/swiper.scss
I made a Sass port of the original Less styles as requested in issue #2159.  Could you include the `.scss` files into the source tree, or it would be better if I create a separate package for these styles?
=> Add Sass Styling

demos/440-change-direction.html, src/components/core/core-class.js
short code in changeDirection() method and add demo
=> Update change direction

src/components/core/update/updateActiveIndex.js
=> fix: fixed runCallbacksOnInit bugs

src/components/thumbs/thumbs.js
If thumbs swiper has virtual slides, active slide in thumbs gallery is not setted properly
https://i.imgur.com/RKAApOz.gifv
Always follow the [contribution guidelines](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md) when submitting a pull request.
=> Fix thumbs swiper with virtual slides

src/components/core/core-class.js
Fix swiper for use with shadow dom components
=> feat(shadow): fix find wrapper

package/src/components/core/slide/slideTo.js
Fixing https://github.com/nolimits4web/swiper/issues/3398
=> Fix snapGrid bug

src/components/core/update/updateActiveIndex.js
Patch for resolving issue https://github.com/nolimits4web/swiper/issues/3487
=> Fixed condition for emitting "slideChange" event

src/components/core/images/loadImage.js, src/components/lazy/lazy.js
Add support for picture element lazy-loading.
I've made some changes on lazy.js to accept data-srcset like used on other pull request example.
Based on #3151 
Maybe solving #3096 #3112 
Test Use: https://aloje.com.br
=> Add support for picture element lazy-loading

src/components/effect-coverflow/effect-coverflow.js
Now you have possibility to use scale parameter in coverflow effect.
=> Scale param for coverflow effect added.

SWIPER-REACT.md
This commit will fix a typo in the react documentation.
=> Fixes typo

src/types/swiper-options.d.ts
Fixes #3743 Added boolean type to swiper-options navigation, pagination and scrollbar props.
=> add some types of swiper-options for React

CHANGELOG.md
=> Fixed typos in CHANGELOG.md

package.json
I notice that homepage url could be https.
=> Chore: update home page schema

src/components/a11y/a11y.js, src/components/pagination/pagination.js
=> feat: support multiple classes in pagination buttonClass

src/types/components/controller.d.ts, src/types/components/keyboard.d.ts, src/types/components/mousewheel.d.ts, src/types/components/navigation.d.ts, src/types/components/pagination.d.ts, src/types/components/scrollbar.d.ts, src/types/components/thumbs.d.ts, src/types/swiper-class.d.ts, src/types/swiper-events.d.ts, src/types/swiper-options.d.ts
=> fix: add missing types

package-lock.json
@nolimits4web Fix CI error by updating the `package-lock.json`.
=> Fix CI Error

src/components/mousewheel/mousewheel.js
Fix: [issue3873](https://github.com/nolimits4web/swiper/issues/3873).
=> Fix issue 3873

src/components/core/events/onTouchStart.js
Fix: [issue3801](https://github.com/nolimits4web/swiper/issues/3801).
=> Fix issue 3801

build/vue/package.json
=> Fix issue  3956

CHANGELOG.md, src/types/components/thumbs.d.ts
Fixed typos in thumbs.d.ts and CHANGELOG.md
=> Fixed typos in thumbs.d.ts and CHANGELOG.md

CHANGELOG.md, src/types/swiper-events.d.ts
Update swiper-events.d.ts
Also fixed a typo in CHANGELOG.md
=> Fixed typo in swiper-events.d.ts

src/components/lazy/lazy.js, src/types/components/lazy.d.ts
=> Fix issue 3928, should not lazy load when swiper not inView.

CHANGELOG.md, src/types/components/pagination.d.ts
Update pagination.d.ts and CHANGELOG.md
(Thanks to @gamtiq for finding him)
=> Fixed typos in pagination params

src/components/core/events-emitter.js
=> Code optimization.

CHANGELOG.md, src/types/swiper-options.d.ts
Update swiper-options.d.ts and CHANGELOG.md
=> Fixed typos in swiper-options.d.ts and CHANGELOG.md

README.md
Update README with relevant build commands for new contributors.
Fix me if something wrong or missing.
=> docs: README update to current build commands

src/types/swiper-events.d.ts
=> fix(react): internal types should be optional

src/types/swiper-class.d.ts
=> fix(types): getBreakpoint

src/components/core/update/updateSlides.js
Modify:
`const previousSlidesGridLength = swiper.snapGrid.length`
to
`const previousSlidesGridLength = swiper.slidesGrid.length`
=> optimized updateslides code

README.md
Adds build scripts docs for angular to README
=> docs: angular build scripts

.gitignore, package/package.json, src/angular/src/swiper.component.ts
use of  `<swiper [virtual]="true">`as a boolean isnt working in prod build.
Error:
```
Error in src/app/app.component.ts (8:53)
Type '""' is not assignable to type 'false | VirtualOptions'.
```
This PR fixes it.
=> fix(angular): input types accept boolean

.github/workflows/test.yml
=> ci: github actions wokrflow init

src/angular/src/swiper.component.ts
=> fix(angular): typing

.gitignore, package/package.json, package/postinstall.js
=> fix: postinstall echo on windows

src/angular/src/swiper.component.html
=> Angular: Fix container-end slot selector

src/components/effect-cube/effect-cube.less, src/components/effect-cube/effect-cube.scss
closes #3069 
before fix: https://stackblitz.com/edit/swiper-demo-23-3d-cube-effect
after fix: https://stackblitz.com/edit/swiper-demo-23-3d-cube-effect-cazhqo
=> fix: cube shadow chrome

.eslintignore, .gitignore, package/package.json, package/postinstall.js
=> fix(swiper5): postinstall echo on windows

CHANGELOG.md
=> Fixed year on the release date of v6.4.6

src/angular/src/swiper.component.ts
=> fix(angular): ssr get attribute

.travis.yml, README.md
Always follow the [contribution guidelines](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md) when submitting a pull request.
=> chore: remove travis ci

playground-angular/src/app/app.component.html, playground-angular/src/app/app.component.ts, src/angular/src/swiper.component.ts
https://stackoverflow.com/questions/65570802/angular-swiper-not-working-when-using-ngif
=> fix(angular): slide change render

playground-angular/src/app/app.component.html, playground-angular/src/app/app.component.scss, src/angular/src/swiper.component.html, src/angular/src/swiper.component.ts
=> fix(angular): custom el config

src/components/core/classes/addClasses.js, src/components/core/core.less, src/components/core/core.scss
closes #3728
#3589
#3649
#3772
thanks @paultuckey your workaround gave the right direction :)
=> fix: swipe on pointer events devices

playground-angular/src/app/app.component.html, src/angular/src/swiper.component.ts
=> fix(angular): ngIf inside swiperSlide

playground-angular/src/app/app.component.html, src/angular/src/swiper.component.ts, src/components/core/core-class.js, src/types/swiper-events.d.ts
=> fix(angular): Cannot set property 'classNames' of undefined

playground-angular/src/app/app.component.html, src/angular/src/swiper.component.html, src/angular/src/swiper.component.ts, src/components/core/core-class.js, src/types/swiper-events.d.ts, src/types/swiper-options.d.ts
#4086 
fix for Angular implemenation
=> refactor(angular): use slideClass property

playground/angular/src/app/app.component.html, playground/angular/src/app/app.component.ts, playground/angular/src/app/app.module.ts, src/angular/src/swiper.component.html, src/angular/src/swiper.component.ts
=> fix(angular): BrowserAnimationsModule slides deletion

playground/angular/src/app/app.component.html, playground/angular/src/app/app.component.ts, src/angular/src/swiper.component.ts
=> fix(angular): autoplay SSR

README.md
adds following badges to readme:
- <img alt="tree-shakeable" src="https://badgen.net/bundlephobia/tree-shaking/swiper" />
- <img alt="types included" src="https://badgen.net/npm/types/swiper" />
=> docs: add tree-shakable and types badges

README.md
Maybe we should add all modules here?
=> Add features section to readme

README.md
Do you think a description necessary for each bullet?
=> docs: features

src/types/components/a11y.d.ts
=> Fixed typo in a11y.d.ts

playground/angular/src/app/app.component.html, playground/angular/src/app/app.component.ts, src/angular/src/swiper.component.ts
=> feat(angular): thumbs & controller support

cypress/integration/modules/a11y.js, cypress/support/commands.js, cypress/test.html, src/components/a11y/a11y.js
=> fix(a11y): space should trigger role button

src/vue/get-params.js
Fix Issue [#4272](https://github.com/nolimits4web/swiper/issues/4272)
=> Fix Issue #4272

README.md
Add 'Major Roadmapped Features' (maybe we should consider another name) to the readme, inspired by https://github.com/11ty/eleventy#major-roadmapped-features
=> docs: Major Roadmapped Features

cypress/integration/modules/a11y.js, cypress/support/commands.js, src/angular/src/utils/utils.ts, src/components/a11y/a11y.js, src/components/core/core-class.js, src/react/utils.js, src/svelte/utils.js, src/types/components/a11y.d.ts, src/utils/utils.js, src/vue/utils.js
=> feat: a11y.slideLabelMessage

playground/angular/src/app/app.component.html, src/angular/src/swiper.component.ts
=> feat: custom html element support

playground/angular/src/app/app.component.html, playground/angular/src/app/app.component.ts, src/angular/src/swiper.component.ts
=> fix: update virtual slides

src/components/navigation/navigation.scss
For some reason, postcss 8 does not allow multiplication by -1
=> fix postcss 8 error

package/package.json
=> Remove svelte as peerDependency

cypress/integration/modules/core.js
=> tests(core): remove it.only

src/angular/src/swiper.component.ts, src/angular/src/utils/utils.ts
=> fix(angular): custom html element support

src/types/swiper-class.d.ts
=> Fixed typo in swiper-class.d.ts

src/angular/src/swiper.component.ts, src/angular/src/utils/utils.ts
=> fix(angular): custom naviation & pagination

playground/angular/src/app/app.component.html, playground/angular/src/app/app.component.scss, src/angular/src/swiper.component.html, src/angular/src/swiper.component.ts
=> feat(angular): use class & ngClass on <swiper> component

src/types/components/keyboard.d.ts, src/types/components/pagination.d.ts, src/types/components/scrollbar.d.ts, src/types/swiper-options.d.ts
Update scrollbar.d.ts
"true" -> "false"
Fix https://github.com/nolimits4web/swiper-website/issues/140
Also fixed typo in swiper-options.d.ts
"navigation" -> "pagination"
and added the `effect` param to the examples
Also fixed typo in keyboard.d.ts
=> Fixed typo in scrollbar.d.ts

.github/ISSUE_TEMPLATE/swiper_angular_issue.yml, .github/ISSUE_TEMPLATE/swiper_core_issue.yml, .github/ISSUE_TEMPLATE/swiper_react_issue.yml, .github/ISSUE_TEMPLATE/swiper_svelte_issue.yml, .github/ISSUE_TEMPLATE/vue_issue.yml
Fixed typos in Issue Templates
=> Fixed typos in Issue Templates

CHANGELOG.md, src/types/components/a11y.d.ts
Update a11y.d.ts
Also fixed a small typo in CHANGELOG.md
=> Fixed previous -> next typo in a11y.d.ts

src/utils/utils.js
=> fix(core): don't extend html elements in SSR

playground/angular/src/app/home/home.component.html, src/angular/src/swiper.component.ts
=> fix(angular): nested swiper

src/components/core/events/onTouchStart.js, src/components/hash-navigation/hash-navigation.js
Fixed typos in comments and function name
=> Fixed typos in comments and function name

playground/core/index.html, playground/core/main.js, src/components/pagination/pagination.less, src/components/pagination/pagination.scss
=> feat(pagination): hide 1 dot pagination

playground/angular/src/app/home/home.component.html, playground/angular/src/app/home/home.component.ts
=> docs(angular): add demo for onSlideChange event handler

src/types/components/controller.d.ts, src/types/components/virtual.d.ts, src/types/swiper-class.d.ts, src/types/swiper-events.d.ts
=> fix: improve typing

src/types/modules/effect-creative.d.ts
=> fix(types): effect-creative `translate`

src/modules/lazy/lazy.js
=> lazy.checkInView option fix

src/modules/pagination/pagination.less, src/modules/pagination/pagination.scss
Added some CSS variables for pagination bullet to :
- Manage size (width & height) of a bullet
- Manage background color of inactive bullet
- Manage opacity of inactive color
I might add a variable to manage gap between bullet too.
Something like :
```scss
.swiper-pagination-bullet + .swiper-pagination-bullet {
margin-left: var(--swiper-pagination-gap, 0px);
}
```
But it might cause issue for RTL
=> Add pagination bullet CSS variables

playground/angular/src/app/home/home.component.html, playground/angular/src/app/home/home.component.ts, src/angular/src/swiper-slide.directive.ts, src/angular/src/swiper.component.html
=> feat(angular): support `data-swiper-autoplay`

src/types/swiper-options.d.ts
Always follow the [contribution guidelines](https://github.com/nolimits4web/swiper/blob/master/CONTRIBUTING.md) when submitting a pull request.
=> fix(core): swiper options effect cards lost

playground/angular/src/app/home/home.component.html, playground/angular/src/app/home/home.component.ts, src/angular/src/swiper.component.ts, src/angular/src/utils/params-list.ts
=> feat(angular): `enabled` prop

src/angular/src/swiper.component.ts
Removed the offending code as discussed in #5006
=> fix(angular): removed stray setIndex debug code (nolimits4web#5006)

src/angular/src/swiper.component.ts
=> feat(angular) add `lock` and `unlock` events

src/types/swiper-options.d.ts
closes https://github.com/nolimits4web/swiper-website/issues/193
=> fix(docs): property -> properly

playground/angular/src/app/home/home.component.html, playground/angular/src/app/home/home.component.ts, src/angular/src/swiper.component.ts
=> fix(angular): `@output` events emitting

playground/angular/src/app/home/home.component.html, playground/angular/src/app/home/home.component.ts, src/angular/src/swiper.component.ts, src/angular/src/utils/get-params.ts
=> fix(angular): toggle input

src/angular/src/swiper.component.ts
=> fix(angular): setElement call updateInitSwiper bug

src/angular/src/swiper.component.ts
https://github.com/nolimits4web/swiper/commit/d48fb1b848c61d79e05f075676b8567952f0d280
https://github.com/nolimits4web/swiper/pull/5296#pullrequestreview-836214645
actually reverting this change: https://github.com/nolimits4web/swiper/commit/ab3a4adbb4e69f04e1790918d801ee2837b8fe61#diff-bfa627463b910d30122bd97c77f46167402610e987ac7922fb67145fb0104525L462
=> fix(angular): `setElement` checks

src/core/slide/slideTo.js
Method src/core/slide/slideTo.js refactored.
No breaking changes, only conditional optimized and duplicate lines of code removed.
=> refactor(core/slide/slideTo): remove duplicate code

src/types/modules/pagination.d.ts
https://github.com/nolimits4web/swiper-website/issues/169
=> fix(types): bullets type should be `Dom7Array`

src/react/params-list.js
Swiper does not respect changes to autoplay module at runtime
fix https://github.com/nolimits4web/swiper/issues/5418
=> Add autoplay to watched modules

playground/angular/src/app/home/home.component.ts, src/angular/src/public-api.ts, src/angular/src/swiper-events.ts, src/angular/src/swiper.component.ts
exported as `SwiperNgEvents`.
Have better naming suggestion?
=> feat(angular): events types

src/angular/src/swiper.component.ts
=> feat(angular): lock output

src/core/modules/resize/resize.js
Fast browser window resize produces `Error: ResizeObserver loop limit exceeded`. The error isn't visible in browser console, doesn't affect functionality, but degrades performance of slider. Solution is taken from https://stackoverflow.com/a/58701523/17278571.
Fixes #5440
=> fix(core): wrap resize observer callback in requestAnimationFrame

playground/angular/src/app/home/home.component.html, playground/angular/src/app/home/home.component.ts, src/angular/src/swiper-slide.directive.ts
https://github.com/nolimits4web/swiper/discussions/5561
=> feat(angular): support `[ngClass]` in swiperSlide

src/vue/swiper.js
=> fix: enabled not working (fix #5611)

.github/ISSUE_TEMPLATE/swiper_angular_issue.yml, .github/ISSUE_TEMPLATE/swiper_core_issue.yml, .github/ISSUE_TEMPLATE/swiper_react_issue.yml, .github/ISSUE_TEMPLATE/swiper_svelte_issue.yml, .github/ISSUE_TEMPLATE/vue_issue.yml
Fix https://github.com/nolimits4web/swiper-website/issues/253
=> Swapped the title and description for these two items in creating a bug for Swiper

.github/dependabot.yml
Adds dependabot for npm packages and GitHub actions
=> chore(ci): add dependabot

demos/index.html
https://github.com/nolimits4web/swiper/discussions/5851
Add an index.html with an index of all the demos to facilitate development and testing :grin:
=> Add index.html page to demos

README.md
=> Fixed periods

src/angular/src/swiper.component.ts
=> feat(angular): slidesPerGroupAuto

src/svelte/swiper-svelte.d.ts
Fixes https://github.com/nolimits4web/swiper/issues/5571
=> Fix autoplay options typescript problem

src/core/loop/loopFix.js
Fixed loop when using custom slideActiveClass
=> Fixed loop usage

src/modules/mousewheel/mousewheel.js
Implementation of issue https://github.com/nolimits4web/swiper/issues/6670.
(Sorry for the add and revert, worked on master first)
=> Mousewheel ignore class

src/copy/package.json
=> fix package.json exports for typescript

.github/ISSUE_TEMPLATE/swiper_element_issue.yml
Add Swiper Element Issue template
=> Add Swiper Element Issue template

src/types/modules/zoom.d.ts
Reference Code:https://github.com/nolimits4web/swiper/blob/master/src/modules/zoom/zoom.mjs
Always follow the [contribution guidelines](https://github.com/nolimits4web/swiper/blob/master/CONTRIBUTING.md) when submitting a pull request.
=> fix:incorrect zoom toggle types

src/core/events/onTouchEnd.mjs
Can't swipe to the last slide with **long touches** when `slidesPerView` is set to `auto`.
https://codesandbox.io/s/swiper-slides-per-view-auto-forked-d4mdyk?file=/index.html
=> fix(core): swipe to last with slidesPerView: auto

src/vue/get-children.mjs, src/vue/virtual.mjs
=> support for vue@2.7

src/modules/navigation/navigation.scss
https://github.com/nolimits4web/swiper/issues/7609
Change order of properties to avoid SASS Deprecation Warning
=> Update navigation.scss to remove SASS Deprecation Warning

src/modules/pagination/pagination.mjs
fixed the BUG at
https://github.com/nolimits4web/swiper/issues/7270
=> fix(pagination) Fixed swiper Infinite loop scroll jumping
