src/idangerous.swiper.js
If you define slidePerView 1.22 together with loop mode the library throws an undefined object exception.
This should fix the loop mode.
=> Fix Loop-Mode with fractional slidesPerView-setting

package.json
There's really no need to store all the project files as a package resources.
=> Restrict list of exported files

src/idangerous.swiper.css
If your document direction is RTL,
You most add "direction: ltr" to 'swiper-container' for fix working Swiper.
=> Add RTL language support

bower.json
The current paths don't compile correctly because they point to the wrong place.
=> Fixing paths to dist files in bower

src/idangerous.swiper.js
Device: Nokia Luma 920
OS: Windows Phone 8.1 Update
Problem: onSlideChangeEnd callback is not executed
Reproduction:
1. You touch a slide and swipe (let's say left)
2. You let the slide go
3. An animation should happen now, but it doesn't, the slide just snaps into it's new position
Description of Solution:
Since there is no animation happening after letting a slide go, the onSlideChangeEnd event is also not fired.
So why there is no animation? Answer: Currently the library starts the animation before setting the duration of the animation. WP8 doesn't like this and skips the animation. By setting the duration of the animation BEFORE starting the animation, everything works as expected.
=> Make onSlideChangeEnd work on Window Phone 8x

gulpfile.js, src/js/a11y.js, src/js/core.js
This PR closes #1130 
- Focusable navigation arrows (not bullets, I thinks arrows are enough)
- Visual feedback when focused on navigation arrows. Currently uses default platform outline, but can be changed to specific arrow color/opacity level.
- Navigation arrows are interactive via keyboard (Enter key).
Also there's a basic ARIA applied for screen readers:
- Notify about prev/next slide
- Notify about first/last slide
=> Keyboard accessibility

src/js/lazy-load.js
Bug I found when using `lazyLoadingInPrevNext`.
=> Invoke correct method to preload slide image

demos/31-custom-plugin.html
The custom plugin uses a path to the build directory which is not available in the normal download.
=> Fix path to js file in custom plugin demo

src/js/core.js
Hi!
I noticed that allowSwipeToPrev -and Next only is used in onTouchMove.
My application is an e-reader for newspapers, and I have placed a empty page first so that page nr.1 is placed to the right. But I want to disable swipeToPrev in portrait-mode. because otherwise my users would be able to swipe to a empty page. And allowSwipePrev works great for this. But they can still navigate their with the keyboard arrow keys!
So my idea is so add allowSlideToPrev -and Next properties, and then check for these in the slideTo-function, and this works really good for me.
What do you think?
=> Added allowSlideToPrev and allowSlideToNext

src/js/keyboard.js
I'm swiping between pretty heavy canvas data, and thought about optimizing navigation with keyboard. So I lock swipes in "onTransitionStart " and then on "onTransitionEnd" I unlock swipes again. This way I  (and with my updated code in handleKeyboard) I can disable stacking of slideTo-calls.
Next slideTo if holding down arrow key will be called when current transition is done.
=> Return false from handleKeyboard if keycode is equal to not allowed direction

src/js/amd.js, src/js/core.js, src/js/dom.js, src/js/mousewheel.js, src/js/swiper-intro.js, src/js/swiper-outro.js, src/js/wrap-end.js
If I include this library with browserify and try to run my unit test, I get this error:
```
Swiper.prototype = {
^
ReferenceError: Swiper is not defined
```
This is because most of the use cases of using the variable `Swiper` assume a browser.  I have slightly modified the code so that the initial creation uses `var Swiper = ...` instead of `window.Swiper = ...`.  At the end of the main file, I then do a `window.Swiper = Swiper;` to make sure it is available globally like it is now.  I also updated the amd script to use `window.Swiper` instead of just `Swiper` (which was just inferring the `window.` anyways).
I tested some of the examples (since there don't seem to be able unit tests) and everything worked fine.  If this could be merged and a new version pushed to npm that would be great …
=> fixed issue with running mocha tests that include this library

src/js/core.js
Trailing comma on last item in object breaks script for some browsers
=> removed trailing comma

src/js/keyboard.js
Hi
I want to set the keyboardControl param in enableKeyboardControl to true, and respectively false in disableKeyboardControl.
I want this functionality because I don't want to call enableKeyboardControl more than once if it is enabled. But as it is now, params.keyboardControl won't change in these functions, so it will always return true if it was enabled on init. So I have no way to check the state as I understand.
It would be nice if we could use this existing property, and not have to add another property reflecting this state.
What do you think of the idea?
=> Sets keyboardControl param in disable and enableKeyboardControl

src/js/core.js
Error fix for params[param].nodeType when params[param] is null because null is an type of object.
=> Error fix for params[param].nodeType when params[param] is null 

src/js/core.js
removing 'detach' variable because is unused.
=> Unused detach variable

demos/16-effect-fade.html, demos/25-hash-navigation.html
Noticed while creating type definitions for Swiper 3.3.0 that in 16-effect-fade.html and 25-hash-navigation.html the paginationClickable property was being passed a selector. In the documentation and after examining Swiper's internal use of this property it is treated only as a boolean.
Typescript defitions for Swiper 3.3.0
https://github.com/WarriorRocker/DefinitelyTyped/blob/swiper/swiper/swiper.d.ts
Let me know what you think.
=> Fix paginationClickable property in demo files to be boolean

src/js/core.js
Implements the feature request described in #1673. Simply a couple of wrappers for toggling s.params.onlyExternal after the Swiper has been instantiated.
=> Add enableTouchControl() and disableTouchControl()

demos/38-jquery-ie9-loop.html, src/js/core.js, src/js/swiper-proto.js
The following use-case was causing the regression error bug:
- Using 'dist/js/swiper.jquery.min.js' on IE9
- Setting 'loop' property on instantiation of Swiper to 'true'
- Using arrow as navigation (swiping was working fine)
If this use-case is happening (requirement on my project) 's.animating' within the 'core.js' will be re-assigned  to 'true' on each click on the arrow/s. Resulting in only one slide change (initial click).
Solution:
- added the lte (lower then or equal) IE9 conditional check in 'src/js/swiper-proto.js' > property 'browser' > property 'lteIE9' (detecting browser by feature instead of version or UA etc.)
- wrapping line 1907 in 'src/js/core.js' method 'slideTo' into the IF statement (if (!s.browser.lteIE9) s.animating = true;). Idea is not to do the re-assignment on …
=> Fixing IE9 issue.

src/js/core.js
Currently Swiper only measures the height of the active slide when setting container height. This fix also looks at other slides in view, and uses the tallest slide's height.
**NOTE:** This fix doesn't take into account sliders with `slidesPerView: 'auto'`, it only ignores it. A more elaborate fix is needed to support that.
=> Fixing autoHeight if slidesPerView is more than 1

src/js/a11y.js, src/js/core.js, src/js/keyboard.js, src/js/lazy-load.js
Currently, it's not possible to change all class names in the settings. I also fixed some hardcoded class names (e.g. `slideClass` or `slideDuplicateClass`, see `src/js/keyboard.js`) that could already be changed in the settings.
=> Add possibility to change all class names

src/js/core.js
#1658 
I've just added the option **normalize** to let you activate another slide when you click it and the all slides are in viewport. It's is useful when using 2 Swipers, one as pagination.
When using **centeredSlides** it's already doing, but it solves the trick when it's not.
=> adding normalize option

src/js/scrollbar.js
This fixes a typo in the disableDraggable function which causes swiper.destroy() to error out when the scrollbar is enabled.
=> Fixes an error on swiper.destroy() when scrollbar is enabled

src/js/hashnav.js
Previously, attachEvents did not fire when there was no hash, since init function returned too early. Thus hashnavWatchState did not work properly; Swiper did not slide anywhere when document.location changed.
All I did was prevent the if statement from returning early, and moved the existing code inside the if statement block.
=> Bug fix: hashnav attachEvents did not always launch at init.

package.json
This fixes Yarn not installing Swiper on Node version < `6.7.0`. Yarn strictly checks for the engine version so it will refuse to install the package if the version is lower than specified on `package.json`. I've tested all the tasks on the build process and they work fine against Node `4.7.0`, so that's the version I specified. It could even run fine on an even lower version as well, but I haven't tested.
Resolves #1964.
=> Downgrade engine version for Yarn compatibility

src/js/core.js
If you want do show/hide with this usage swiper:
https://github.com/nolimits4web/Swiper/blob/master/demos/23-thumbs-gallery.html 
The position of centered slide is broken.
Demo:
http://www.giphy.com/gifs/26hirxQ7trqmlipQ4
=> Bug fix centered slides show/hide position

src/js/core.js
A specific constant exists for the `pagination-clickable` class, but isn't currently used. Now it does!
=> Use clickable class instead of modifier with postfix

demos/40-infinite-loop-with-multiple-slides.html, src/js/core.js, src/less/core.less
I encounter the same problem as #1800 
When using infinite loop with slidesPerGroup, some slides will repeat if the number of slides doesn't fit the group.
For example, 
If there are 10 slides with following settings:
```js
slidesPerView: 4,
slidesPerGroup: 4,
loop: true,
```
it becomes:
page 1: 1, 2, 3, 4
page 2: 5, 6, 7, 8
page 3: 9, 10, 1, 2
page 1: 1, 2, 3, 4
1 and 2 are repeated in page 3.
Thus, this PR adds the feature to fit the last page with blank slide(s) when the new parameter `fitSlideGroupWithBlank` is set to true.
Then page 3 will become: 9, 10, (empty), (empty)
=> Add blank slides to fit slides per group

src/js/init.js
Clean up jQuery data and object reference attached to the DOM element, remove reference to container and wrapper.
=> Better cleanup when instance is deleted

README.md
Changed compliations to compilations in the readme.
=> Tiny spelling fix in README.md

src/js/core.js
It is related to https://github.com/nolimits4web/Swiper/pull/2150
Sorry, I forgot to update the situation that if slides.length can be divided by slidesPerGroup.
In this case, there will be one more blank group in the end.
=> Prevent adding extra blank items

src/components/core/update/updateSlides.js
Since "support" is no longer a property of the Swiper core class, a check for "support.flexbox" throws an error for an invalid object access.
=> Bugfix: flexbox support check

src/components/core/events/onTouchMove.js, src/components/effect-fade/effect-fade.js, src/components/effect-flip/effect-flip.js
This PR removes obsolete transitionend prefixed events as discussed at https://github.com/framework7io/Framework7/issues/1288 and at https://github.com/framework7io/Framework7/pull/1849
=> Remove obsolete prefixed event names

src/components/core/breakpoints/setBreakpoint.js
Sets a default loopedSlides count to avoid NaN. The problem resulted in `swiper.slideTo(NaN, 0, false)`. It only occurred when using using both loop and breakpoints, and initialising on a viewport within a breakpoint.
Also Fixes #2243
=> Set default loopedSlides to avoid NaN

src/js/core.js
This PR exports the defaults object as Swiper.defaults so others can use it. This is specially useful for wrappers like ember-cli-swiper that need to manage the parameters that the components can use.
See https://github.com/Suven/ember-cli-swiper/pull/32
=> Export defaults in Swiper object

src/components/autoplay/autoplay.js
Reverse direction of Swiper autoplay
This feature allows to play slides in reverse, simply setting the `reverseDirection` property to true and the slides will play in reverse.
Other than this being a nice feature, it allows vertical top-to-bottom direction autoplay much like a news-feed effect.
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
=> Add support for reverse autoplay

src/components/keyboard/keyboard.js
This pull request should fix the problem with keyboard navigation. The problem was with detection of the swiper inside of the viewport.
The previous code did an unnecessary calculations, but the actual offset state is properly calculated within `offset` method of the `Dom7` library so there is no need to do it once again.
=> Fix detection statement whether a swiper is in the viewport - fixes #2380

src/components/pagination/pagination.js, src/components/pagination/pagination.less
Hi,
right now the dynamic bullets in the pagination are limited to one active and 4 more, 2 for each side.
i added code to have more main bullets instead of just one, 
it feels more smooth when there is room for the active bullet to move in.
i'm using your code in a mobile-web project at my company
and i would really like if the code would become part of the package instead of me using locally the modified version.
i'll be happy to hear any comments,
have a nice day,
tzvika
=> dynamic bullets: multiple main bullets

API.md
Due to extra newlines, the table format of the v3 API document was formatted incorrectly. This change fixes that.
=> Fixes a markdown issue with v3 API docs

src/components/a11y/a11y.js
a11y should be enabled by default like in most frameworks, it should be optout.
=> enable a11y by default

src/components/mousewheel/mousewheel.js
Fix Issue #2513 I raised earlier today. 
Added mouseenter and mouseleave handlers to set a flag which conditionally lets the mousewheel handler complete. If the scroll/ mousewheel event is triggered while the mouse is on an element that is not a Swiper element, the event will not propagate.
=> Handle mouseenter and mouseleave events

src/components/core/breakpoints/setBreakpoint.js
fix #2566
Fixed using breakpoint with loop will get wrong realIndex on init. Using `swiper.initialized` to prevent `slideTo` when init swiper.
=> fixed breakpoint with loop getting wrong realIndex when on init

src/components/core/loop/loopFix.js
Fixed loop behavior, which reported in issue #2647.
In 10 slides and 2.5 slidesPerView case,
* Left arrow button stops between Slide 9 and Slide 8 => Fixed
* 2 swipes are need to move from Slide 9 to Slide 8 => Fixed
* Slide 8 is often not shown in left of Slide 9 => Fixed
Test is at https://jsfiddle.net/kochizufan/su1ka5ov/
=> Fix loop behavior (Issue #2647)

src/components/core/events/onTouchMove.js
This PR fix swiper.onClick don't occur in Chrome on Old Android OS (Android Lollipop - Marshmallow)
This bug exists even in the latest Chrome, if Android OS is old.
The reason of this bug is, swiper.onTouchMove events are fired even subtle touch move in Old Android's Chrome
So, swiper.onTouchMove event forces to change swiper.allowTouch property to "false" every time, hence occurring of swiper.onClick is canceled in swiper.onTouchEnd.
To avoid this, I add the code
`
if (swiper.params.threshold && Math.sqrt(Math.pow(diffX, 2) + Math.pow(diffY, 2)) < swiper.params.threshold) return;
`
in swiper.onTouchMove.
By this, if finger moving distance is less than params.threshold, swiper.allowTouch not change to false.
So, swiper.onClick event works.
If user don't set params.threshold value, this …
=> Fix swiper.onClick don't occur in Chrome on Old Android OS

src/components/scrollbar/scrollbar.js
This pull request fixes a typo in `scrollbar.js` which prevents using the param `passiveListeners` in this specific module.
=> Fix typo in passive listeners.

src/components/core/events/onTouchStart.js, src/modules/observer/observer.js
I found that the `observerUpdate` event is being dispatched for every mutation in a MutationEvent.
This causes serious performance issues depending on the number of mutations that are present in the MutationEvent.  I saw that all the methods that react to the `observerUpdate` will safely accommodate this change.  Calling `observerUpdate` multiple times will have the same end result as dispatching it once within a callstack.
And to make things run just a little smoother, I decided to add the ability to run this within an animation frame to help keep the ui from locking up.
=> #2730: Ensure observerUpdate event is only dispatched once on a MutationEvent

src/components/virtual/virtual.js
This is a fix for: https://github.com/nolimits4web/swiper/issues/2755
Before, on `beforeInit` event, `swiper.virtual.update()` being executed when value for `swiper.activeIndex` was not set. That led to Swiper rendering `0`&`1` slides, even if the `initialSlide` was set to something else.
`virtual.update()` is not nessesary in the `beforeInit` callback, since its being called in the `setTranslate` callback and by that time `swiper.activeIndex` was initialised with the right  `initialSlide` value.
=> Remove swiper.virtual.update() from beforeInit callback

src/components/core/classes/addClasses.js, src/utils/browser.js
I want to use **swiper** in a Universal Windows Platform App (UWP) on a surface tablet.
The swiper does not work with touch events on this device, because UWP Apps on Windows 10 are using the Edge Browser.
It seems like the Edge Browser needs the `WP8 Touch Events Fix` in ` /src/components/core/classes/addClasses.js` too.
I've added the `isEdge` property to not confuse anyone.
Because it's not the Internet Explorer, but it behaves like that.
=> Fix touch swiping in UWP app on surface tablets

src/components/core/defaults.js, src/components/core/events/onTouchStart.js
I have a window mousemove event to save x and y mouse coords.
I try to add the event with the capture option but on mousedown Swiper fire the prevent default.
I added this option `touchStartPreventDefault` to prevent this behavior, and manualy prevent default mousedown event only to an image inside the swiper-slide (for example).
Before this i try to change `touchEventsTarget` with for example `wrapper` but it doesn't work.
Example here:
https://codepen.io/exodusanto/pen/OovKEq?editors=0010
If you move the mouse the coords info change but if you start drag swiper the event mousemove freeze until you stop the drag.
=> Touch start prevent default option

src/components/core/events/onTouchStart.js
Hot fix #2794 
I saw `swiper.allowTouchMove` and I thought that `swiper` has inside all params but you extends swiper instance and add `allowTouchMove` property on another file 😖.
I fix it with the correct `params` object
=> Hot fix for touchStart prevent default issue

package-lock.json, src/components/core/breakpoints/setBreakpoint.js
breakpoints parameters like spaceBetween and other breakpoint variables brought in sometimes as strings so the fix to this breakpoints responsive mode is to convert these variables to integers where appropriate (except 'auto' of course) so example slidesPerView and slidesPerGroup (I need this for breakpoints functionality) 
This is a pretty straight forward fix, have a look at the pull request and the commit.
I've also created a build in my fork, called it v4.4.2 of swiper. see my fork here: https://github.com/entreprise7pro/swiper
=> breakpoints source code fix, see issue https://github.com/nolimits4web/swiper/issues/2789

src/components/core/defaults.js, src/components/core/events/onTouchStart.js
There is a specific scenario where events in the slider will be blocked. I put a Stackblitz up to simulate the issue: https://stackblitz.com/edit/react-ts-iniqzm
- if I have a slide with an element inside
- the slide has a `noSwipingClass` set to `selected`, so when my element is select it will not slide
- in the container I have an event that happens `onMouseUp` that logs `hello` on the console
- if my element is not selected and I slide it will not trigger the `hello` event
I've been using an workaround by setting
```ts
this.swiper.touchEventsData.formElements = '*';
```
This way the current swiper code does this internally
```js
if ($(e.target).is(data.formElements)) preventDefault = false;
```
Which triggers the `event.preventDefault()` and allows my `hello` even to execute.
Instead …
=> Add forcePreventDefault flag

src/components/scrollbar/scrollbar.js
Fixes #2840
Further thinking on what's on the issue, I think the logic deciding what events to attach (at least for the scrollbar) can be simplified in just weather touch is enabled or not. The touchEvents() function takes care of which desktop events to use.
This may be applied to the main part where a similar decision making is made in this regards: 
https://github.com/nolimits4web/swiper/blob/aef21b8e6add21c86cc8681be83ac4647dc23c7a/src/components/core/events/index.js#L30-L45
https://github.com/nolimits4web/swiper/blob/aef21b8e6add21c86cc8681be83ac4647dc23c7a/src/components/core/events/index.js#L71-L86
I can submit a different PR for that if OK
=> Scrollbar events based only on Support.touch

src/components/core/update/updateSlides.js
In grid mode, the number of full columns is incorrectly calculated in updateSlides.js causing data-row-swiper to be incorrectly calculated and subsequently incorrect margins to be applied to the slides.
For example, a 8 x 3 grid (slidersPerView=3 and slidesPerColumn=8) yields 24 slides. If there are 17 slides in the collection then there are 2 full columns.
Existing logic calculated this as 3 - ((8 * 3) - 17) = -4. Clearly there cannot be -4 complete columns.
Correct logic should yield the integer component of (17 / 8) which is 2.
=> Fix incorrect calculation of the number of full columns.

src/components/core/classes/addClasses.js
This could allow users to use CSS to hide/show elements in the HTML which only have relevance when the Slider is initialized.
For example, I might use CSS to hide the Pagination and Nav Buttons if the Slider is not Initialized.
.swiper-container .swiper-pagination ,
.swiper-container .swiper-button-prev ,
.swiper-container .swiper-button-next {
display: none;
}
.swiper-container-initialized .swiper-pagination ,
.swiper-container-initialized .swiper-container .swiper-button-prev ,
.swiper-container-initialized .swiper-container .swiper-button-next {
display: initial;
}
=> Adds "[prefix]-initialized" Class to the Container Element.

src/utils/support.js
pointerEvents: navigator.maxTouchPoints should > 0 , when pointerEnabled and PointerEvent no exitsts.
It's cause none simulate touch in chrome 49
```js
// src/components/core/events/index.js#L30
if (!Support.touch && (Support.pointerEvents || Support.prefixedPointerEvents)) {
// actual go here
target.addEventListener(touchEvents.start, swiper.onTouchStart, false);
document.addEventListener(touchEvents.move, swiper.onTouchMove, capture);
document.addEventListener(touchEvents.end, swiper.onTouchEnd, false);
} else {
// should go here
if (Support.touch) {
const passiveListener = touchEvents.start === 'touchstart' && Support.passiveListener && params.passiveListeners ? { passive: true, capture: false } : false;
target.addEventListener(touchEvents.start, swiper.onTouchStart, passiveListener); …
```
=> fix: support pointerEvents

src/components/thumbs/thumbs.js
Fixes the bug 'Cannot read property `indexOf` of undefined' described in step 1 of #2990 that sometimes occurs on use of thumbnails
=> Bugfix thumbnails

src/components/keyboard/keyboard.js
`PageUp`/`PageDown` keybindings are widely-used keybindings in hardware presentation clickers. This pull request binds `PageDown` to move to the next slide & `PageUp` to move to the previous slide.
=> Add PageUp/PageDown keybindings

src/components/core/core.less, src/components/core/core.scss
your sourcecode does this, which effectively overwrites my usage of margin-classes:
```css
.swiper-container {
margin: 0 auto;
}
```
```html
<div class="some-gallery swiper-container   margin1">
<div class="swiper-wrapper">
...
```
And I'd argue it's not swipers job to declare margin before or after it;
I like to avoid extra wrappers wherever possible. :)
=> Swiper shouldn't declare margins on top and bottom aswell

src/utils/dom.js
I'm using dom7 modular in a project together with swiper and patched some methods to be more jquery compatible (e.g. added second argument for toggleClass).
But now my methods gets randomly overidden (depending on webpacks processing order).
=> Don't override Dom7 methods if already declared

demos/450-watchSlidesVisibility.html, src/components/core/update/updateSlidesProgress.js
Because in the “updateSlidesOffset” method,DOM offsetLeft and offsetTop do not compute decimals,So when slide offestLeft or offsetTop is decimal,  it will be issues. 
When you need to get the visibility parameters of slide, you will find that the invisible slide also has "swiper-slide-visible" className.
I set the error range between 1PX to control the visibility of the slider.
The example is in the demos files: "demos/450-watchSlidesVisibility.html"
=> fixed "swiper-slide-visible" className shows up when it shouldn't

src/components/core/events/onResize.js, src/components/core/update/updateSlides.js
In IE the width returned from `getPropertyValue('width')` on elements with a `box-sizing: border-box` styling doesn't include paddings as in other browsers.
This is an issue that arrises in IE when using `slidesPerView: 'auto'` and having paddings on each slide together with a `box-sizing: border-box;` styling on the slides.
Here's an example: https://s.codepen.io/DKvistgaard/debug/BXyZyx/XBrGRZbEvGGM
Also see the issue #2897 for more info.
=> SlideSize to include paddings for border-box elements in IE (fixes #2897)

src/components/core/update/updateProgress.js
in rtl mode the prev button will be hidden after touch event although if we don't reach the start of the swiper (the right side of it) so I made some update to fix this bug
=> rtl bug fix

src/components/core/core-class.js, src/components/core/events/index.js, src/components/zoom/zoom.js
If the page is loaded via an app's embedded webview, the slides will not be released when we swipe far enough away out of the webview edges. It looks like as it get stuck. This PR solve the problem.
=> listen to touchcancel event and treat it as touchend

src/components/core/loop/loopCreate.js
Modified **loopCreate()** to set *loopedSlides* to a float rounded up to the nearest whole number.
original line in **loopCreate()**
```
swiper.loopedSlides = parseInt(params.loopedSlides || params.slidesPerView, 10);
```
new line
```
swiper.loopedSlides = Math.ceil(parseFloat(params.loopedSlides || params.slidesPerView, 10));
```
This modification allows *slidesPerView* to be a float value while also being able to swipe next through the loop.
Test: https://plnkr.co/edit/T6Upr5sMv2j7sM7MPCkw?p=preview
=> Fixed #3025

src/components/core/events/onTouchEnd.js
Modified **onTouchEnd()** to check if the event target is either of the navigation buttons before short swiping
original block in **onTouchEnd()**
```
if (swiper.swipeDirection === 'next') {
swiper.slideTo(stopIndex + params.slidesPerGroup);
}
if (swiper.swipeDirection === 'prev') {
swiper.slideTo(stopIndex);
}
```
new block
```
if (e.target.className !== 'swiper-button-next' && e.target.className !== 'swiper-button-prev') {
if (swiper.swipeDirection === 'next') {
swiper.slideTo(stopIndex + params.slidesPerGroup);
}
if (swiper.swipeDirection === 'prev') {
swiper.slideTo(stopIndex);
}
}
```
This modification will prevent short swipes from firing when clicking on either of the navigation buttons
Test: https://plnkr.co/edit/1QlfdfMKiYKIDR2VLntQ?p=preview
=> Fixed #3126

src/components/core/events/onResize.js, src/components/mousewheel/mousewheel.js
When create swiper with horizontal scroll only (forceToAxis)
```
mousewheel: {
forceToAxis: true,
invert: true,
},
```
it doesn't scroll if try to scroll with `Shift + Scroll` combination
Checked in all browsers (except safari) + mobile + win touchpad, works fine
=> Make possible of work shift + mouse wheel (horizontal scroll)

src/components/core/events/onTouchMove.js
Fixes #2956
[MDN currently describes](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/targetTouches#Browser_compatibility) `targetTouches` as not supported but this isn't the case, at least in iOS 13.
Most of the time referencing `targetTouches` is ok however sometimes it doesn't contain any `Touch` objects inside the `touchmove` event. This happens when the drag was initiated outside of the Swiper container.
=> Use changedTouches instead of targetTouches inside of onTouchMove

src/components/core/events/index.js, src/components/core/events/onTouchMove.js
_Copied from PR https://github.com/nolimits4web/swiper/pull/3259 for 4rd version_
Fixes #2956
MDN currently describes targetTouches as not supported but this isn't the case, at least in iOS 13.
Most of the time referencing targetTouches is ok however sometimes it doesn't contain any Touch objects inside the touchmove event. This happens when the drag was initiated outside of the Swiper container.
=> Swiper4 - Use changedTouches instead of targetTouches inside of onTouchMove

src/components/pagination/pagination.js
This fixes the issue of pagination bullets at the end of a loop not having the ```-main``` class as per the ```dynamicMainBullets``` property [as described in the original issue](https://github.com/nolimits4web/swiper/issues/3029#issue-428709036).
Added a conditional in ```pagination.js``` to check if ```bulletIndex``` is at the end of the loop minus ```dynamicMainBullets```.
Test: https://plnkr.co/edit/JbSx3nijaSgs45qwXUr2?p=preview
=> Fixed #3029

src/components/core/events/onTouchEnd.js
This PR fixes #3301 by limiting the maximum swipe duration when `freeModeSticky` is active, as follows: 
* If the `moveDistance` is less than the current slide size, then the duration is limited to the default swipe speed (`params.speed`)
* If the `moveDistance` is 1x to 2x the current slide size, then the max duration is limited to 1.5x the default swipe speed
* Otherwise the max duration is limited to 2.5x the default swipe speed. 
The underlying problem is caused because the duration was previously calculated without taking into account the extra distance required to snap to the nearest slide when `freeModeSticky` is active.
You can use the same site from #3301 to verify that this PR is working: 
`git clone https://github.com/justingrant/swiper-repro.git && npm i && npm start`
To …
=> Fix duration when freeModeSticky is active

src/components/core/slide/slideToClosest.js, src/components/mousewheel/mousewheel.js
This PR fixes #3154 by enabling smoother and faster inertial scrolling when `freeModeSticky` is on. Changes include:
* Fixes the problem where you're "locked out" of wheel scrolling for a few hundred msecs after the end of a momentum wheel scroll. With this PR you can repeatedly scroll with wheel or two-finger trackpad gestures without any lags or pauses.
* Avoids the delay between the last `wheel` event and snapping to the closest edge. With this PR, the snap happens during the deceleration phase of the momentum scroll instead of waiting 500ms after the last `wheel` event is received, so the snap happens 600ms+ sooner than current behavior.
* Biases snapping in the direction of the scroll, instead of slowing down and then reversing a long distance.  If the projected end of the scroll is …
=> Faster & smoother mousewheel inertial scrolling

src/components/core/events/onResize.js
This PR fixes #2708 by handling resizing in the same way regardless of whether `freeModeSticky` is active or not.  See https://github.com/nolimits4web/swiper/issues/2708#issuecomment-518935544 for an explanation of the problem and a description of the thinking behind this PR. 
You can use the same site from #3301 to verify that this PR is working: 
`git clone https://github.com/justingrant/swiper-repro.git && npm i && npm start`
To verify the PR is working, simply resize the browser. If the fix works, after resizing the slide should stick to the edges. (Without this fix, the slide will not be stuck to the edge after resizing.)
=> Fix `freeModeSticky` resizing behavior to ensure it stays sticky after a resize

src/components/core/update/updateSlides.js
Fix to issue #3222. Slides could get misplaced with wrong order and margin if `slidesPerColumnFill = row` and `slidesPerGroup > 1` and `slidesPerColumn > 1` and the last group was not filled up with slides.
=> Fix issue with wrong row/column if not full groups

src/components/core/loop/loopFix.js
Remove redundant condition in loopFix function.
The condition make a gap when click prev button.
There is swiper option:
`swiperOption: {
slidesPerView: 'auto',
centeredSlides: true,
loop: true,
loopedSlides: 3,
navigation: {
nextEl: '.swiper-button-next',
prevEl: '.swiper-button-prev'
}
}`
=> remove redundant condition

src/components/core/check-overflow/index.js
Modified checkOverflow() to account for ```slidesOffsetBefore``` and ```slidesOffsetAfter```. This fixes a [bug](https://github.com/nolimits4web/swiper/issues/3005) where ```watchOverflow: true``` wouldn't work with ```slidesOffsetBefore``` and ```slidesOffsetAfter``` set to a non-zero value.
Test: https://plnkr.co/edit/o6gQxkfqcVjYEF3rPskx?p=preview
=> Fixed #3005

src/components/thumbs/thumbs.js
In this image we use slidesPerView of 1.5 for the main images, the connected thumbnail slider uses this value to activate multiple thumbnails. In our usecase we only want the first (real) slide to get activated. CSS workarounds would be ugly or impossible.  
That's why I suggest to add an option for it. I've set the default value to the current behaviour. Additionally i rounded down the thumbsToActivate value in case someone is using it (as we did) with a fractional value (a small logic fix).
=> [feature] thumbs options - add option to control multiple slide activation

package/components/core/core.scss
Add SCSS interpolation for `--swiper-theme-color` variable when not building from source.
See #3327
=> Add SCSS interpolation for --swiper-theme-color variable when not building from source

src/components/a11y/a11y.js
I found this bug when I was investigating a problem, that user specified `init()` callback not be fired when we have only one initial slide.
My trace route is: `init() > swiper.preloadImages() > swiper.update() > swiper.updateProgress() > swiper.emit('reachEnd toEdge') > a11y::on::toEdge() > swiper.a11y.updateNavigation()`.
Since we haven't met this problem ever before, I think it may be a recent change to cause it easier?
=> fix: should judge existence of `navigation` in a11y module

src/utils/class.js
Modified class.js ```once``` event listener. Moved ```handler.apply(self, args)``` to run after ```if (onceHandler.f7proxy)```. This should fix a bug where this event runs more than once. See [issue 3084](https://github.com/nolimits4web/swiper/issues/3084).
=> Fixed #3084

playground/index.html, src/components/mousewheel/mousewheel.js
As I've already well explained in this two issues (nolimits4web/swiper#3325 and nolimits4web/swiper#3326) the user experience scrolling the slider was very bad due to the _momentum_ of the mouse/trackpad. This was particularly visible on Mac OS.
I've been fixing the behaviour by instructing the script to animate the slider when only if the scroll direction has changed or the scroll delta has increased. These two are sufficient to differentiate the scroll events triggered by a user and the ones triggered by the _momentum_.
You can try it on my fork using the playground.
=> FIX scroll wheel unwanted frozen effect

package/package.json
It will fix install issues with yarn berry (v2)
Currently install is broken on yarn berry due to an error with node -e.
```
[eval]:1
console.log('u001b[35mu001b[1mLove Swiper? Support Vladimir's work by donating or pledging on patreon:u001b[22mu001b[39mn > u001b[32mhttps://patreon.com/vladimirkharlampidiu001b[0mn')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: missing ) after argument list
at new Script (vm.js:86:7)
at createScript (vm.js:268:10)
at Object.runInThisContext (vm.js:316:10)
at Object.<anonymous> ([eval]-wrapper:9:26)
at Module._compile (internal/modules/cjs/loader.js:945:30)
at evalScript (internal/process/execution.js:80:25)
at internal/main/eval_string.js:23:3
```
Use echo instead of node is a better choice because you are not dependant of node eval …
=> [fix] use echo instead of node -e

CHANGELOG.md
Minor changelog typo fix for the 4.5.1 section: `slidesPerColumFill` -> `slidesPerColumnFill`
=> Fix changelog typo (slidesPerColumFill -> slidesPerColumnFill)

src/components/core/slide/slideNext.js
Same method call runs after `if` block.
=> Remove redundant method call

demos/211-slides-per-group-skip.html, src/components/core/breakpoints/setBreakpoint.js, src/components/core/defaults.js, src/components/core/events/onTouchEnd.js, src/components/core/slide/slideNext.js, src/components/core/slide/slideTo.js, src/components/core/slide/slideToClosest.js, src/components/core/update/updateActiveIndex.js, src/components/core/update/updateSlides.js
**Problem / Current Limitation:**
The current `slidesPerGroup` implementation strictly enforces groups to be of constant size. Previously, a `slidesPerGroup = 'auto'` option has been requested, but implementation seems complex and cumbersome.
**Use Cases:**
- One of the use-cases for a more dynamic `slidesPerGroup` setting was the ability to treat a cover slide differently, to replicate a flipbook / magazine. see #1422
- For such use-case, the new property `slidesPerGroupSkip` allows users to configure the amount of slides to treat as single groups, before starting to swich into grouped mode.
**Example:**
http://cdn.magloft.com/github/swiper/index.html
**The parameter works in the following way:**
1. If `slidesPerGroupSkip` equals `0` (default), no slides are excluded from grouping, and …
=> Implement `slidesPerGroupSkip` parameter

src/components/mousewheel/mousewheel.js
The pr is to solve [#3382](https://github.com/nolimits4web/swiper/issues/3382) and [#2624](https://github.com/nolimits4web/swiper/issues/2624). when refreshing the page and don't move the mouse, it does't trigger 'mouseenter' event, this result in mousewheel fail.
I add another condition `!target[0].contains(e.target)` to solve it. It means when  trigger `mousescroll` event, we get the event target, and if the event target is in swiper target 
```
let target = swiper.$el;
if (swiper.params.mousewheel.eventsTarged !== 'container') {
target = $(swiper.params.mousewheel.eventsTarged);
}
```
we don't return.
I have tested in my project and it works.
=> fix mousewheel fail#3382

demos/381-ratio-breakpoints.html, src/components/core/breakpoints/getBreakpoint.js
**Problem / Current Limitation:**
Currently, the `breakpoints` param only supports absolute unit values, e.g. the width of the window in pixels. For some applications, e.g. on mobile devices, this turns out to be a limitation, preventing an easy way to implement certain logic like portrait / landscape switches.
**Use Cases:**
- Implementing a breakpoint switch between portrait and landscape by using `@1.00` (width/height ratio above 1.00 / square).
- More granular control of slide layout, by tuning the ratio values to guarantee a certain width / height ratio of visible slides.
**Example:**
Located in [`demos/381-ratio-breakpoints.html`](https://github.com/MagLoft/swiper/blob/963f622d329568bc28fb639a6858178f3c6b8cf6/demos/381-ratio-breakpoints.html#L82)
**The parameter works in the …
=> Implement ratio breakpoints

src/components/core/core-class.js
Swiper.js currently prevents any mousedown/up events being fired within its container. _Except_ for form elements. However, it does not include `<label>` elements as being form elements.
Typically the label is also an element that can be interacted with within a form, like with checkboxes and radiobuttons. Especially if you create custom checkboxes and radiobuttons with only CSS, where you typically hide the actual checkbox/radiobutton `<input>` element via CSS and style the `<label>` (including its `:before` and `:after` pseudo elements) to represent the checkbox/radiobutton and its current visual state (using `input:checked ~ label`).
But in such a case this means the radiobutton or checkbox cannot actually be interacted with within a Swiper.js container, as the `<input>` element itself …
=> Add label to formElements

src/components/zoom/zoom.js
The API is saying 
- `mySwiper.zoom.in(); | Zoom in image of the currently active slide`
- `mySwiper.zoom.out(); | Zoom out image of the currently active slide`
~ https://swiperjs.com/api/#zoom
The issues #3450 and #2827 describe how to reproduce a bug that does not zoom into the _currently active slide_.
This fix sets the correct slide instead of zooming into the previous slide.
=> fix zoom on wrong slide - #3450 #2827

src/components/effect-coverflow/effect-coverflow.js
For the coverflow effect, one can use `stretch` to define how many pixels the prev/next sliders go behind the front one. So if slider is 1000px, you can put `900` and only 10% is shown. However if this slider is responsive (width: 70% or something) and becomes 800px, 500px, etc. width, then the `900` is obviously wrong.
With this tiny PR, one can put `'10%'` instead, so stretch will be relative based on the actual width. I hope this can be approved as it's probably useful in plenty of today's responsive sites. Thanks!
=> Coverflow stretch percentage for responsiveness

src/components/navigation/navigation.less, src/components/navigation/navigation.scss
**Before**:
**After**:
Looks like the focus ring has a rendering glitch due to inherited page `line-height`, that is likely > 1.0. Set the pseudo-element `line-height` to a neutral value of 1.0 fixes it. 
Tested with latest Safari, Chrome and Firefox.
=> Fix focus ring rendering glitch due to inherited page line-height.

src/components/hash-navigation/hash-navigation.js
When using nested swipers you can check if you have hash navigated to a slide of the nested swiper with the slideChange event and position the main swiper on the slide where the nested swiper is located. However if the nested swiper slide that is being hash navigated is the active slide, the SlideChange event does not happen, hence the need for the HashChange event in this particular case.
=> Add an event on hash change

src/components/core/events/onTouchMove.js
We are receiving a reasonable amount of ReportingObserver errors on our swiper component. The error is:
```
ReportingObserver [intervention]: Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted
```
To be honest I am not sure how to test this as I havent been able to trigger this issue myself, but I used this SO as reference and the error it self also exactly explains what the issue is: https://stackoverflow.com/questions/26478267/touch-move-getting-stuck-ignored-attempt-to-cancel-a-touchmove
=> fix: only cancel cancelable touchmove events

CHANGELOG.md
FIxed a typo in latest version 5.4.0 changelog (**lates** to **latest**) and update the release dates using a more proper way
=> FIX typo and update dates in changelog

package-lock.json, package/package.json
Hello! I wanted to follow up on an issue that came across ionic's issue tracker.
https://github.com/ionic-team/ionic/issues/21138
TL;DR, the update to `ssr-window` fixed some ssr bugs, but the package.json in the package dir did not get the ssr-window version bump.
This PR should address that.
=> fix sub-package.json

src/components/pagination/pagination.js
Removed the restriction on one unique pagination element.
I would like to be able to use several instances of swiper on the page, in which there are two pagination elements (on top of the slide and below)
=> Fix in pagination detect uniqueNaVElements

src/components/core/check-overflow/index.js
Adds check for `swiper.navigation` before calling `swiper.navigation.update()`. 
This avoids "_Uncaught TypeError: Cannot read property 'update' of undefined_" when navigation is not configured.
=> Adds check for navigation object. Fixes #3620

src/components/mousewheel/mousewheel.js
When scrolling, the carousel often jumps two pages of slides instead of one, due to inertia of the scroll. It's particularly noticeable with a mac trackpad.
To improve, I've added preventSwipeThresholdDelta and preventSwipeThresholdTime params to the mousewheel module, so that:
1. only scroll events over that delta threshold will be acknowledged.
and
2. only scroll events which happen after a threshold time in milliseconds will be acknowledged.
To make this work, you can add the following params to the config:
```
{
slidesPerView: 3,
slidesPerGroup: 3,
spaceBetween: 20,
direction: 'horizontal',
speed: 500,
mousewheel: {
forceToAxis: true,
// This only allows scrolls with a delta greater than 120 to be acknowledged. 
preventSwipeThresholdDelta: 120,
// This only allows scrolls once every 3 …
```
=> Mousewheel: add threshold for wheel scroll event

src/react/virtual.js
At version 6.1.1  swiper/react won't support RTL direction in virtual mode.
This RP is to fix this. #3755
=> fix: support react/virtual rtl direction

src/components/a11y/a11y.js
Hi there,
This is a proposed fix for issue #3417. Please go easy on me, I hope this is useful as I don't want to raise an issue and not try t work towards a solution.
If pagination.renderbullet is set, (and the user wishes to implement their own html code to render each bullet), hand off responsibility of making that code accessible by not forcing `role="button"` and `aria-label` on it. Adding these unasked might even hurt the accessibility of what the user is trying to achieve.
I tested this locally and it worked as expected for me as summarized above!
=> #3417 if pagination.renderbullet is set, don’t add role/aria-label

src/components/mousewheel/mousewheel.js
There is a small typo in src/components/mousewheel/mousewheel.js.
Should read `momentum` rather than `momuntum`.
=> docs: Fix simple typo, momuntum -> momentum

playground/index.html, src/components/a11y/a11y.js, src/types/components/a11y.d.ts
This pull request is related to https://github.com/nolimits4web/swiper/issues/3149.
It contains three new parameters for a11y:
- containerMessage (String)
- containerRoleDescriptionMessage (String)
- itemRoleDescriptionMessage (String)
Their default value is null, considering that the a11y community doesn't share a common opinion about aria-roledescription (s. https://github.com/nolimits4web/swiper/issues/3149).
There are some new functions in the a11y section:
- getRandomNumber(size), returning a random number, used to create a random id for the wrapper element.
- addElRoleDescription($el, description), adding the attribute "aria-roledescription" with value "description" to $el
- addElControls($el, controls), adding the attribute "aria-controls" with value "controls" to $el
- …
=> A11y enhancements

src/components/core/events/onTouchStart.js
Problem 
`$targetEl.closest` does not find element with swiping class if the element is within a web component with shawroot. 
Fix 
Replace targetEl to be the first element in the event touch path
=> Fix no swiping class in shadow copmonent

scripts/build-js-core.js, scripts/build-react.js, scripts/build-svelte.js, scripts/build-vue.js
You build scripts using ENV variables without cross-env, as a result, I didn't succeed to run a build on Windows.
This PR adding `cross-env` before `MODULES=` the same way as it's done in `package.json` scripts. 
now:
```js
await exec.promise(
`MODULES=${format} npx babel src --out-dir ${outputDir}/${format} --ignore ${ignore.join(
',',
)}`,
);
```
to:
```js
await exec.promise(
`cross-env MODULES=${format} npx babel src --out-dir ${outputDir}/${format} --ignore ${ignore.join(
',',
)}`,
);
```
Error log:
```bash
$ npm run build:prod
> swiper-src@6.3.4 build:prod D:\projects\swiper
> cross-env NODE_ENV=production node scripts/build
'MODULES' is not recognized as an internal or external command,
operable program or batch file.
'MODULES' is not recognized as an internal or external command, …
```
=> fix(build): add cross-env to support windows

src/components/core/slide/slideTo.js
Perform the type checking on the `index` argument before using its value inside the `slideTo()` method.
Fixes #3897.
=> #3897 | Type-check the `index` argument

src/types/components/a11y.d.ts, src/types/components/mousewheel.d.ts, src/types/components/navigation.d.ts, src/types/components/thumbs.d.ts, src/types/components/virtual.d.ts, src/types/swiper-options.d.ts
This PR adds `null` types. Example:
```typescript
/**
* String with CSS selector or HTML element of the element that will work
* like "prev" button after click on it
*
* @default null
*/
prevEl?: CSSSelector | HTMLElement;
```
Optional character `?` tells Typescript that it accepts `undefined` but not null, but according to the `@default` null is acceptable.
So `null` type is missing here and in places like this. 
closes #3866
=> fix(types): add null types

src/components/pagination/pagination.js
I've made a mistake in PR #3913 
Extra braces after the class name:
```js
`.${params.bulletClass.replace(/ /g, '.')}}<-- two braces instead of one
```
this PR fixes it.
=> fix(pagination): bullet class mistake

src/components/core/update/updateSize.js
I believe this is a real typo, when detecting if there is a height in options, you always test height and width, then without the width in options, this will always fall, and there are so many issues with this height problems.
Always follow the [contribution guidelines](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md) when submitting a pull request.
=> fix a typo in updateSize()

src/components/keyboard/keyboard.js
Fix issue #3895, by ignore the origin [0,0] inView.
[0,0] not inView could avoid keyboard trigger slide change in hidden swiper.
When hidden swiper , the swiperCoord was:
```
0: (2) [0, 0]
1: (2) [NaN, 0]
2: (2) [0, NaN]
3: (2) [NaN, NaN]
```
=> Ignore the origin [0,0] inView.

src/components/mousewheel/mousewheel.js
This PR mainly solves the following scenarios: When swiper nested swiper, all the parent and child have scrollbar, when scroll reach the edge, should not disable parent swiper.
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Swiper demo</title>
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
<link rel="stylesheet" href="../../swiper/package/swiper-bundle.css">
<style>
html,
body {
position: relative;
height: 100%;
}
body {
background: #eee;
font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
font-size: 14px;
color: #000;
margin: 0;
padding: 0;
}
.swiper-container {
width: 100%;
height: 100%;
}
.swiper-slide {
text-align: center;
font-size: 18px;
background: #fff;
/* Center slide text vertically */ …
```
=> [enhancement] Scroll on edge should not disable parent swiper when nested.

src/react/swiper-slide.js, src/svelte/swiper-slide.svelte, src/vue/swiper-slide.js
Vue, Svelte and Vue checking `swiper-slide-duplicate next` class to identicate `slideData.isNext` variable.
But I see that the right class is `swiper-slide-duplicate-next` (**with** dash)
=> fix: swiper-slide-duplicate-next class typo

scripts/build-svelte.js
closes #4013 
maybe #3961
@btakita
This PR includes `swiper.svelte` & `swiper-slide.svelte` files according to your request.
Is just putting it in the root enough or they should be exported somewhere?
=> build(svelte): include *.svelte files into package

package/package.json
closes  #3985 
looks like echo with \n is failing in postinstall script on windows.
In windows 10 it's not crashing but it's not writing the second line:
```
$ npm run postinstall
> swiper@6.4.1 postinstall D:\projects\swiper\package
> echo "Love Swiper? Support Vladimir's work by donating or pledging on patreon:
> https://patreon.com/vladimirkharlampidi
"
"Love Swiper? Support Vladimir's work by donating or pledging on patreon:
```
On Windows NT and probably other old windows versions its crashes.
echo ** & echo ** should work fine on both platforms I think.
=> fix: postinstall echo on windows

src/components/pagination/pagination.less, src/components/pagination/pagination.scss
Setting `border-radius: 100%` can actually _decrease_ roundness on some browsers.
=> Reduce pagination border-radius

src/swiper-react.d.ts
Привет, земляк! Love your library ❤️
I recently upgraded the Swiper from v4 to v6 in my project and decided to replace `react-id-swiper` with your official `swiper/react` components. It works great, but my CI fails with the following error:
```
node_modules/swiper/swiper-react.d.ts:6:11 - error TS2430: Interface 'Swiper' incorrectly extends interface 'Pick<HTMLAttributes<HTMLElement>, "hidden" | "dir" | "slot" | "style" | "title" | "id" | "color" | "translate" | "prefix" | "children" | "defaultChecked" | ... 236 more ... | "onTransitionEndCapture">'.
Types of property 'onKeyPress' are incompatible.
Type '((swiper: Swiper, keyCode: string) => void) | undefined' is not assignable to type '((event: KeyboardEvent<HTMLElement>) => void) | undefined'.
Type '(swiper: Swiper, keyCode: string) => …
```
=> Fix React types

src/types/components/autoplay.d.ts, src/types/components/pagination.d.ts, src/types/components/scrollbar.d.ts, src/types/swiper-events.d.ts, src/types/swiper-options.d.ts
https://github.com/nolimits4web/swiper-website/pull/97
Maybe you prefer to change variable name from `mySwiper` to something else? e.g `swiperRef`?
=> refactor(types): use const in examples

.github/stale.yml
Changing label `wontfix` to `stale`. I think it will be a more proper label?
adding following labels to exceptions:
- feature request
- probably bug
- bug confirmed
- in progress
if merged: rename wontfix to stale in https://github.com/nolimits4web/swiper/labels
=> ci: change stale label & add exception labels

src/svelte/swiper.svelte
svelte had a mistake. should be `container-start` instead of `content-start`.
https://swiperjs.com/svelte#slots
closes #4150
=> fix(svelte): slots container start & end

.github/workflows/build.yml, .github/workflows/formatting.yml, .github/workflows/lint.yml, README.md
split test workflow into three workflows:
- Formatting (`npm run check-format`)
- Lint (`npm run lint`)
- Build (`npm run build:prod`)
I think this way indication will be more informative and in the future, it will be easier to add new tests, like e2e and etc.
What do you think?
=> ci: split test to three ci workflows

src/react/get-params.js, src/svelte/get-params.js, src/vue/get-params.js
fix: #4181 
In the case of `{}`, `needsNavigation`, `needsPagination`, and `needsScrollbar` will be true, so if each props is false, the initial value is given so that element is null.
=> fix: navigation, pagination, scrollbar props #4181

src/react/params-list.js
Hi, 
When using one of `observer`, `observeParents`, `observeSlideChildren`, one will get this error and Swiper will ignore those params and pass them over to the root 'div' resulting in these errors: 
(reproducible by adding the params to the demo App.js)
```
react-dom.development.js:88 Warning: Received `true` for a non-boolean attribute `observer`.
If you want to write it to the DOM, pass a string instead: observer="true" or observer={value.toString()}.
in div (created by Swiper)
react-dom.development.js:88 Warning: React does not recognize the `observeParents` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `observeparents` instead. If you accidentally passed it from a parent component, remove it from the DOM …
```
=> fix(react): add 'observer', etc. to params-list

src/components/core/update/updateClickedSlide.js
Use case: tens of slides of which only some are visible/enabled at a time by toggling `swiper-slide` on both the thumbs slider and the main slider (and updating the slider ofc). More specifically, a product page where the product pictures are updated depending on the selected color.
```
<div class="swiper-container>
<div class="swiper-wrapper">
....
<div class="not-a-slide-for-now"></div>
<div class="swiper-slide"></div>
<div class="swiper-slide"></div>
<div class="not-a-slide-for-now"></div>
.....
</div>
</div>
```
results in Swiper setting `swiper.clickedIndex` to the DOM position of the slide node instead of the position relative to the actual slides (i.e. `.swiper-slide`). In my use case, this breaks the thumbs module which is not able to properly update the clicked slide in the main …
=> fix(core): correcly update clickedSlide when other elements are present in slides wrapper

package/package.json, scripts/build-js-core.js
These two small changes are the result of one hard day of work as a programmer with 19 years of experience trying to make Swiper work with Svelte and Snowpack.
1. `peerDependencies` is needed to avoid a second Svelte instance that almost completely stops Swiper from working.
There redundant`^` in the PR, you can remove it like this: `"svelte": "3.x"`, but everything works with it too.
2. `export const __esModule = true;` in `swiper.esm.js` is needed because of double `.default` attribute bug.
I'm tried to describe it here: https://github.com/nolimits4web/swiper/issues/4297, there same problem, but that commit didn't solve it completely.
=> Fix running with Snowpack

src/components/core/update/updateSlides.js
This is a fix for a bug I have encountered. 
In my case, the swiper with `slidesPerView: 'auto'` has an extra empty space after the last slide, which is visible if you scroll to the end of the gallery.
I don't know if this fixes any other issues that have been reported before.
=> Fix getPropertyValue call in updateSlides

src/components/keyboard/keyboard.js
This PR follows on from [my comments](https://github.com/nolimits4web/swiper/pull/3922#issuecomment-806026531) on a previous inView PR.
If a Swiper instance is initialised and subsequently hidden, the inView flag will be set based on the dimensions that the element previously had, because `swiper.height` and `swiper.width` are cached values. Referencing the element’s height properties directly addresses this.
(I wondered whether `swiper.updateSize()` should be used here, but it’s no help as it will only update width and height values that are greater than 0, which hidden elements won’t be.)
=> Avoid using cached dimensions for keyboard inView calculations

src/utils/dom.js
We are creating a web component for clients to embed on their websites. For some Weebly sites, they define a `remove` method on the `Array.prototype` with the default of `writable: false`. This causes a TypeError when swiper tries to run:
> Uncaught TypeError: "remove" is read-only
>     js dom.js:41
>     js dom.js:40
Using `Object.defineProperty` rather than `$.fn[methodName] =` avoids trying to overwrite the array property.
=> Use Object.defineProperty do define dom7 methods

.browserslistrc, package.json
Move browserlist configurations from `package.json` to `.browserslistrc` file with following settings:
```
last 2 version
> 1%
not IE 9-10 # Swiper not supporting IE 9-10 To opt-in, remove the 'not' prefix on this line.
not IE 11 # Swiper not supporting IE 11
```
that resolves to:
```
$ npx browserslist
and_chr 85
and_ff 79
and_qq 10.4
and_uc 12.12
android 81
baidu 7.12
bb 10
bb 7
chrome 86
chrome 85
chrome 84
edge 86
edge 85
firefox 82
firefox 81
firefox 80
ie_mob 11
ie_mob 10
ios_saf 14
ios_saf 13.4-13.7
ios_saf 13.3
ios_saf 12.2-12.4
kaios 2.5
op_mini all
op_mob 59
op_mob 12.1
opera 71
opera 70
safari 14
safari 13.1
samsung 12.0
samsung 11.1-11.2
```
=> chore: browserlist

src/utils/dom.js
**Issue**
This is to fix the following error when using swiper.js with shadow root web component which is caused by (https://github.com/nolimits4web/swiper/commit/628980a93c9ea7f1fb10a7fe1ad47d5ac98f804f#diff-94256a3f213e569269dd6afb8702cbd9e477199f5d1c6c1ff0e4c263dff2afbfL81). 
`Cannot assign to read only property 'children' of object '[object Array]' ;`
**Reason for this change**
Following the previous implementation on shadow root enable component (https://github.com/nolimits4web/swiper/blob/32092ae9544b0ba3ecc6c3b65346afa546d0547d/src/components/core/core-class.js#L418), We need the property self itself to be `writable` in order to reassign the children to return slot item and return the correct wrapper children elements
=> fix(utils): dom not writeable

src/react/swiper.js
Due to react strict mode additional checks, swiper was not being updated correctly, specifically in virtual mode. Code change of the PR will make sure that it works on strict mode without any issues.
You can replicate issue by creating react virtual swiper and adding slides dynamically in development with react strict mode enabled. After these changes, it seems to be working just fine in development with react strict mode.
=> Make swiper update for virtual mode React.StrictMode compatible

README.md, package/package.json, package/postinstall.js
This PR implements `core-js` postinstall script for swiper.
Looks like `core-js` did really good job for postinstall message:
- shows once in 3 minutes (write a file in temp folder, using its `mtime`)
- not showing message in CI
- ability to block ads via multiple env variables and cli arguments
```js
var DISABLE_OPENCOLLECTIVE = is(env.DISABLE_OPENCOLLECTIVE);
var SILENT = ['silent', 'error', 'warn'].indexOf(env.npm_config_loglevel) !== -1;
var OPEN_SOURCE_CONTRIBUTOR = is(env.OPEN_SOURCE_CONTRIBUTOR);
```
Original: https://github.com/zloirock/core-js/blob/master/packages/core-js/postinstall.js
Also, I've added an instruction on how to block banner based on:
https://github.com/zloirock/core-js/blob/eb8f4e1df395c6abc8b679cd56fe476e9f155ced/README.md#postinstall-message
=> feat: core-js postinstall script

src/types/components/controller.d.ts
Regarding the documentation `control` could be  Swiper instance or array with Swiper instances.
Read more - https://swiperjs.com/swiper-api#controller-methods.
=> Fix control type in ControllerOptions interface

src/swiper-react.d.ts
Add the missing type for [SwiperSlide render function](https://swiperjs.com/react#swiper-slide-render-function) of React,
=> feat(react): add the missing render function type

src/types/swiper-class.d.ts, src/types/swiper-options.d.ts
Noticed a typo in the demo documentation. Found two places where it was used incorrectly. Changed them from "interractions" to "interactions".
=> Fix typos on L#33 and L#167

src/components/pagination/pagination.scss
Fixes nolimits4web/swiper#4553
Currently the implementation of scss interpolation causes a build error. This PR updates the syntax to prevent that.
=> Fix scss interpolation error

src/components/core/breakpoints/getBreakpoint.js
Fixes issue: https://github.com/nolimits4web/swiper/issues/4682
If merged, this will use the [window.matchMedia API](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) instead of doing a comparison with the window.innerWidth, which can be flakey in some devices.
This also attains the benefit of making the breakpoint election closer to the CSS counterpart in media queries.
Browser support for window.matchMedia is wide ( https://caniuse.com/matchmedia ) and has no known gotchas associated (apart from using addEventListener on it in Safari, which we don't need).
=> Fixes safari scroll issue

src/utils/utils.js
Angular SSR build error:
run `npm run angular:dev:ssr` on `master` to reproduce.
```
ERROR RangeError: Maximum call stack size exceeded
at Array.filter (<anonymous>)
at extend (D:\projects\swiper\dist\demo\server\home-home-module.js:7616:55)
at extend (D:\projects\swiper\dist\demo\server\home-home-module.js:7637:15)
at extend (D:\projects\swiper\dist\demo\server\home-home-module.js:7637:15)
at extend (D:\projects\swiper\dist\demo\server\home-home-module.js:7637:15)
at extend (D:\projects\swiper\dist\demo\server\home-home-module.js:7637:15)
at extend (D:\projects\swiper\dist\demo\server\home-home-module.js:7637:15)
at extend (D:\projects\swiper\dist\demo\server\home-home-module.js:7637:15)
at extend (D:\projects\swiper\dist\demo\server\home-home-module.js:7637:15)
at extend …
```
=> fix(core): don't extend html elements

build/vue/package.json, package/vue/package.json, src/swiper-vue.d.ts
This adds proper TypeScript definitions to the Vue components.
I'm not fully sure everything is 100% good, but it was tested on another project and seems to work fine there, so I figured I'd upstream it.
~~It is probably missing some things like the emits, but it has all the (current) attributes defined.~~ Emits have been added, so it should have everything now.
I was a bit lost with the multiple package.json files in multiple places, so feel free to correct me if I messed something up :smile:
Fixes #3916 
**Edit:** I went over the typings again and fixed a bunch of props, all the defaults and added typings for all the emits/event callbacks.  
This should now be pretty much complete.
=> Add Vue component typings

.github/workflows/issue-close-require.yml
> Please provide a link to a repo that can reproduce the problem you ran into. You can fork one of our [demos](https://swiperjs.com/demos) in codesandbox to get start. A reproduction is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "missing demo" label. If no reproduction **is provided after 3 days, it will be auto-closed**.
=> chore: auto issue close on missing demo

src/svelte/init-swiper.js, src/svelte/swiper.svelte
Add a new "modules" property to the Svelte component. To solve the problem with installing additional Swiper modules when used in SvelteKit.
Fix #4705
=> Fix #4705. Install modules in SvelteKit

src/utils/utils.js
Mock window object is very frequent in server side rendering, the `isNode` judge is inaccurate。
Maybe we should judge further
=> fix: fix server side judge (close #4787)

src/components/core/events/onTouchStart.js
Previously, we modified the targetEl to ensure `element.closest(swipingClass)` to always finding the correct element. But it does not work cross browser since event path is different from safari to chrome. This refactor introduce a new method to find the closest matching element with nested shadowRoot, so its now working the same way as the non shadow components. 
So swipe action trigger inside shadow-component will be blocked if either `<Element>` or `<Inner-element>` contains no swiping class. 
`<Element class="no-swiping">`
`<Inner-element class="no-swiping">`
`<shadow-comp />`
`     <Inner-element>`
`</Element>`
=> refactor(touchevent) -  improve shadow swiping class check

src/modules/a11y/a11y.js
When I using the a11y module, the `aria-label` and `aria-controls` values applied to the navigation buttons are incorrect.
Reproduction code:
```javascript
import Swiper, { A11y, Navigation } from "swiper";
new Swiper(".swiper", {
modules: [A11y, Navigation],
a11y: {},
navigation: {
nextEl: ".swiper-button-next",
prevEl: ".swiper-button-prev",
},
});
```
```html
<div class="swiper">
<div class="swiper-wrapper">
<div class="swiper-slide">Slide 1</div>
<div class="swiper-slide">Slide 2</div>
<div class="swiper-slide">Slide 3</div>
</div>
<button class="swiper-button-prev" type="button">Previous</button>
<button class="swiper-button-next" type="button">Next</button>
</div>
```
Result:
```html
<button class="swiper-button-prev swiper-button-disabled" disabled="" tabindex="-1" …
```
=> fix(a11y): fix argments for `initNavEl()` method

src/vue/swiper-slide.js, src/vue/swiper-vue.d.ts
I believe this is just a bug that should be fixed since `swiperRef` props is *actually* not a required prop. 
it caught my eye thanks to Volar
=> fix: make `swiperRef` prop not required in SwiperSlide vue component

CHANGELOG.md, src/types/modules/effect-creative.d.ts
Fixed typo `progressMultipler` -> `progressMultiplier`
Fix https://github.com/nolimits4web/swiper-website/issues/191
P.S. @nolimits4web You might want to take a look at this too: https://github.com/nolimits4web/swiper-website/issues/169
Thanks.
=> Fixed typo `progressMultipler` -> `progressMultiplier`

cypress/integration/modules/core.js, src/core/loop/loopCreate.js
issue: https://github.com/nolimits4web/swiper/issues/5172
can not init an empty swiper after this PR was merged: https://github.com/nolimits4web/swiper/pull/5117
=> fix(core): fallback $selector to $wrapperEl if no children exist

src/core/events/onTouchEnd.js, src/core/update/updateClickedSlide.js
Fixed can not get clicked slider in shadow root issue
=> Fixed can not get clicked slider in shadow root issue

cypress/integration/modules/a11y.js, cypress/support/commands.js, src/modules/a11y/a11y.js
https://github.com/nolimits4web/swiper/issues/3149#issuecomment-941194570
=> feat(a11y): add `aria-current` to current bullet

src/copy/package.json
Related to https://github.com/sveltejs/kit/issues/3015 and a few similar Issues
The "svelte" tag missing from package.json seems to cause some errors when building svelte kit applications.
In my testing adding this line to the package.json fixes the problem completely and there are no more errors.
=> (fix)Added "svelte": "./swiper.esm.js" to package.json

.github/workflows/build.yml, .github/workflows/e2e.yml, .github/workflows/formatting.yml, .github/workflows/lint.yml
Run CI on Swiper8 (and future Swiper7) branches.
I considered adding it as `Swiper*`, but not sure if it will work (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches) also I dont think we want it to run on < Swiper6 branches.
=> chore(ci): run on branches 7, 8

src/vue/get-children.js
this fixes `TypeError: originalSlots[slotName] is not a function` error during HMR in vue by ensuring the function exists.
I havn't opend a issue because it is quite some work to provide a repo and the change is just an assertment.
But I'm not the only one getting this error https://github.com/ionic-team/ionic-framework/issues/24134
=> fix(vue): HMR error

src/modules/effect-coverflow/effect-coverflow.js
For a project I need to have a coverflow effect that only zoom on the current Item. The coverflow effect is nice but it's not possible to lessen the scaling effect. With this proposal a custom function can be used as a modifier to handle more complex scaling for the coverflow effect.
For instance : 
```js
modifier: (v) => between(1, -1, Math.round(v))
```
Would create a scaling that won't affect the elements further they are from the center.
=> feat(coverflow) : allow function modifier

src/modules/thumbs/thumbs.js
There is a weird situation in React / Next when you can switch between multiple instances of the Thumb swiper when switching between pages. It hits some edge cases of the Thumb module where it calls transitions and updates on a swiper which is destroyed, which obviously causes a ton of errors.
This MR aims to be a bit more defensive about these things to avoid trying to trigger transitions or updates on destroyed swipers.
Give me a shout if you want me to explain further or if I missed a critical step.
I struggled reproducing it in a small example, because it's linked to some pretty complex navigation behaviour in Next. But I have a production environment application I can point you to that triggers it an awful lot. I can always send a link to that one in a DM.
=> fix(core) Don't process transitions or updates on Thumbs module if swiper is destroyed

src/core/grab-cursor/setGrabCursor.js
The values of the `grab` and `grabbing` style properties are supported from   
Chrome v68+, and Firefox v27+ without vendor prefixes.
https://caniuse.com/css3-cursors-grab
According to the [browserslist](https://github.com/nolimits4web/swiper/blob/65f96c13707c0301b1f4b32cd108540d8126342b/.browserslistrc) rule, Chrome and Firefox are supported up  
to the latest version 5, and Safari only supports 13 or higher.  
```env
IOS >= 13
Safari >= 13
last 5 Chrome versions
last 5 Firefox versions
Samsung >= 12
```
But now Chrome version is 99, Firefox is 98 and Safari is 15.
Therefore, the `-webkit` and `-moz` vendor prefixes in cursor style are unnecessary,
=> Remove unnecessary vendor prefixes

src/types/modules/pagination.d.ts
Currently both `formatFractionCurrent` and `formatFractionTotal` accept only callbacks which return a number. This makes it impossible write functions like this when using TypeScript (without using `any`):
```ts
pagination: {
el: '#swiper',
formatFractionCurrent(number) {
const formatter = new Intl.NumberFormat('en-US', { ... })
return formatter.format(number)
},
},
```
The above code produces this error: `Type '(number: number) => string' is not assignable to type '(number: number) => number'.`
Since the values returned by theese functions are directly used inside the DOM7 elements `.text()` functions (see [this](https://github.com/nolimits4web/swiper/blob/95c882c50a798ebe7adc20fcb61765aace0edbfc/src/modules/pagination/pagination.js#L184) and …
=> fix(pagination): formatter functions now accept strings as return values

src/shared/effect-init.js
Hello
I'm using the react components with in a fairly complex component using the virtual settings. To force a full rebuild of swiper (e.g. while toggling between fullscreen and not fullscreen view) I update the `key` param. 
By doing so I experienced that an unhandled exception in the `requestAnimationFrame` enqueued by `on('virtualUpdate')`. 
Chrome: `TypeError: Cannot read properties of undefined (reading 'length')`
Firefor: `TypeError: swiper.slides is undefined`
I suppose this happens because the requested animation frame is being processed after or while the change of the `key` reset the swiper object. 
I've only added a check if `swiper.slides` is set at all and could remove the error in my code.
Thank you!
=> Fix: "TypeError: Cannot read properties of undefined (reading 'length')" in on('virtualUpdate') by checking if swiper.slides is set

src/modules/history/history.js, src/types/modules/history.d.ts
- [ADDED] (keepQuery) New option to keep the query string parameters when changing user when navigating
- [FIXED] History back via browser button not working
- [ADDED] typing for History plugin options
> - enabled?: boolean
> - keepQuery?: boolean
=> History plugin fixes and new option adding

src/core/events/onTouchStart.js
This pr fixes the following issues
- getRootNode console error when el is undefined 
- pass in dom7 element to the `closestElement` for better support
=> fix - use target el instead of ev target

src/svelte/swiper.svelte
The Svelte type definitions for custom events are declared as:
```typescript
declare class Swiper extends SvelteComponentTyped<
SwiperProps,
{
swiper: CustomEvent<void>;
autoplayStart: CustomEvent<[swiper: SwiperClass]>;
// ...
lazyImageLoad: CustomEvent<[swiper: SwiperClass, slideEl: HTMLElement, imageEl: HTMLElement]>;
// ...
}
```
I couldn't find those in the [sources](https://github.com/nolimits4web/swiper/blob/master/src/svelte/swiper-svelte.d.ts), so I assume they're [generated](https://github.com/nolimits4web/swiper/blob/master/scripts/build-types.js) during the build process.
As you can see, an event handler subscribing to one of these events, should receive an array with either a single element (i.e. the swiper instance) or more parameters.
Theres a bug in the event delegation …
=> fix incorrect parameters in event dispatching in Svelte

src/core/slide/slideToLoop.js
You should check **slideToLoop** function for Number type as you did in **slideTo**, because in case with custom pagination, developer may use own structure with data attributes and pass those arguments to **slideToLoop**. 
In my case I have broken pagination because **slideToLoop** function returned '35' with Math '3' + swiper.loopedSlides // 5
```
const index = Number(event.target.dataset.slideto); // '3'
if (this.options.loop) {
this.slider.slideToLoop(index); //  => '35'
} else {
this.slider.slideTo(index); // => 3
}
```
=> Fix type Number in slideToLoop.js

src/modules/a11y/a11y.js
Related issue: #5782
This is an attempt to solve the error when slideLabelMessage is set to null in a11y settings. Seems to work with a quick test.
Food for thought: slideLabelMessage should be null by default, instead of `slideLabelMessage: '{{index}} / {{slidesLength}}',`. It's not practical to add text-overriding slide numbering for screen-readers. I decided to not include that null-default in my PR though at this time.
=> Allow slideLabelMessage: null

src/modules/thumbs/thumbs.js
The thumbs active class get's applied and removed right after when the thumbs slider slides the next group of thumbs into view. This only happens when using the library or framework components as those are [emitting](https://github.com/nolimits4web/swiper/blob/master/src/core/core.js#L298) the `_slideClass` update event as part of [sliding to](https://github.com/nolimits4web/swiper/blob/master/src/modules/thumbs/thumbs.js#L166) the next thumbs group. At this time they do not yet contain the class information of the new active thumb, then the active thumbs class [gets toggled ](https://github.com/nolimits4web/swiper/blob/master/src/modules/thumbs/thumbs.js#L196) via direct dom manipulation and afterwards the emitted events from before that where being queued are executed and remove the …
=> fix(thumb): active class gets removed

src/vue/swiper.js
Hello,
While using Virtual module, Vue displays the warning below
This PR fixed it.
=> fix(vue): virtualUpdate event is not declared

src/solid/swiper.js, src/solid/virtual.js
This allows events to be assigned to the slides as usually
Before it didn't work:
```html
<Swiper>
<SwiperSlide>
<button onClick={() => window.alert("clicked")}>
Click me!
</button>
</SwiperSlide>
</Swiper>
```
Now it works
=> Stop using cloneNode in sliders without loops in SolidJS

README.md
Since it took me more than 15 minutes to find the legacy documentation and other people might have [the same problem](https://github.com/nolimits4web/swiper-website/issues/188), I'd like to propose to link this docs right within the readme file.
=> Add link to legacy API documentation

src/react/get-children.js
Fixes [#4413](https://github.com/nolimits4web/swiper/issues/4413)
Replaces strict `displayName` check with `includes` check to allow different `displayNames` for components that act as `SwiperSlide` as long as their `displayName` includes the phrase `SwiperSlide`.
=> Allow React SwiperSlide children as long as displayName includes SwiperSlide

src/types/modules/autoplay.d.ts
Autoplay typing misses some members that might be handy to have (such as `paused` and `pause()`). This change fixes it.
=> Types: add missing AutoplayMethods members

src/angular/src/utils/params-list.ts
Without this `_slidesPerGroup` param, using the following config doesn't take `slidesPerGroupAuto` into account:
```javascript
config = {
slidesPerView: 'auto',
slidesPerGroupAuto: true,
navigation: true,
}
```
A temporary workaround could be defining it in `extendDefaults`:
```javascript
SwiperCore.extendDefaults({
slidesPerGroupAuto: true,
});
```
Fixes https://github.com/nolimits4web/swiper/issues/5932
=> fix(angular): slidesPerGroupAuto is missing in params list for angular

src/vue/swiper-slide.js
In [this PR](https://github.com/nolimits4web/swiper/pull/4992) the `swiperRef` was made optional in the Vue `swiperSlide`, which will throw if during mount the swiperRef is absent.
=> 🐛  Fix swiperRef for Vue swiperSlide

src/types/swiper-options.d.ts
This fix aims to improve readability of the `breakpoints` attribute option in the documentation
=> Fix minor sentence construction issue

src/modules/a11y/a11y.js
Fix:
- check if focus event triggered by touch
- don't jump the slide element
The problem has been discussed several times and a solution has already been implemented for desktop click events.
On mobile devices with touch gestures, however, the error is still present. If a UI element like select field or button is clicked in a slide element, the slide jumps to the first position.
Exactly as it is desired for the focus events. (if you navigate with tabulator key through the slider).
--> The problem was, with a touch event, the focus event is always triggered. For this I have now implemented a query.
Similar problems:
* #5962 
* #5878 
* #5814 
* #5513 
* #5625 
Always follow the [contribution guidelines](https://github.com/nolimits4web/swiper/blob/master/CONTRIBUTING.md) when submitting a …
=> fix: mobile touch on focusable elements jumps element to first position

src/modules/a11y/a11y.js
Fix #6223 JS error "swiper.a11y is undefined"
=> Fix #6223 JS error "swiper.a11y is undefined"

src/core/core.less, src/core/core.scss
Adding the `scroll-snap-stop` property makes the CSS Swiper behaves much more like the JS Version. Especially on Android the Swiper skips some slides when `cssMode` is enabled. By adding `scroll-snap-stop`, the Swiper stops after one slide. Also tested with vertical slides.
| No Scroll Snap Stop      | Scroll Snap Stop |
| ----------- | ----------- |
| <video src="https://user-images.githubusercontent.com/39862171/209677646-3343270e-1822-4525-8754-369121ba6bcd.mp4"></video>  | <video src="https://user-images.githubusercontent.com/39862171/209677748-88f3e3c0-e1c8-45fe-85cc-47111b714c72.mp4"></video>  |
=> chore(css-mode): add scroll snap stop

src/modules/navigation/navigation.js
With swiper version <= 8 it was possible to use multiple classes in `disabledClass`, `navigationDisabledClass` and `lockClass` option. I tried to replicate this feature by just spliting the classes at each whitespace. According to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList?retiredLocale=de#examples) `.classList.add()` and `.classList.remove()` both accept multiple classes.
This PR should fix #6344
=> fix(navigation): allow multiple classes in navigation options

src/modules/autoplay/autoplay.js
Added a null check to "proceed" function so it doesn't run when the swiper doesn't exist used the logic in "onTransitionEnd" for consistancy purposes, tested the fix on my project and it works correctly now...
The problem is described in this issue: https://github.com/nolimits4web/swiper/issues/6261
and this: https://github.com/nolimits4web/swiper/issues/5244
It probably has some specific trigger conditions but it doesn't matter on this fix because it's adding null checks which are never a bad thing.
=> Fixing autoplay undefined error

src/core/events/onResize.js
We had a crash this morning that you can see below:
I think what's happening is that:
* A resize occurs
* This schedules a timeout to resume the autoplay, checking that it should do so before scheduling the timeout
* Before the timeout's callback fires, the autoplay goes away, presumably because the user has moved on to a different page
* The timeout fires and does not check again for the existence of the autoplay, which causes the crash
This just duplicates the check for needing to resume the autoplay within the callback. I debated about whether all three checks were needed but went for the maximal approach just to be sure... happy to tweak that if needed.
=> Fix a crash with resize when the autoplay has gone away during timeout

src/modules/pagination/pagination.less, src/modules/pagination/pagination.scss
Added the feature to manage the border radius value for pagination bullet.
You can change the value in the same way as the bullet size or color:
```scss
.my-swiper {
--swiper-pagination-bullet-width: 48px;
--swiper-pagination-bullet-height: 4px;
--swiper-pagination-bullet-border-radius: 0;
}
```
=> Add pagination bullet border-radius CSS variable

src/modules/controller/controller.js
=> fix(controller): prevent controlled swipers from being called when destroyed

src/types/modules/pagination.d.ts
Fix mismatch between types and code examples.
=> Fix pagination.d.ts render functions

src/core/core.js
Related to: https://github.com/nolimits4web/swiper/issues/6496
This way we avoid Swiper to think a single tap is a double tap when we do it very fast, for example at Cypress tests.
=> Initialize lastClickTime to very old time

src/components-shared/params-list.js, src/core/core.js, src/core/defaults.js, src/core/update/updateActiveIndex.js, src/shared/process-lazy-preloader.js, src/types/swiper-options.d.ts, src/vue/swiper-vue.d.ts, src/vue/swiper.js
Add option to preload a number of next and previous images, based on the new method of lazy loading.
This replaces the functionality lost when the lazy module was removed in v9.
Implemented in the core, based on my inital attempt in #6416.
=> feat: lazyPreloadPrevNext option to preload prev/next images

src/modules/controller/controller.js
Fixes to address this issue [#6552](https://github.com/nolimits4web/swiper/issues/6552)
I did some debugging to fix this bug and found a solution.
Check if the swiper controller is destroyed before the `setTranslate`, `setTransition` functions run.
[In other PR](https://github.com/nolimits4web/swiper/pull/6501), the above two functions are executed and checked for destruction within the setControlledTranslate and setControlledTransition functions, but I think it would be nice to check for this in advance to avoid running unnecessary logic.
This is my first open source PR. Feedback is always welcome.
=> add a conditional to early return if the swiper controller is destroyed

src/element/swiper-element.js
To reproduce the bug: Embed into a website.
Fixes the below issue where the build crashes when minified:
Minified Code Below: 
```
paramsList.forEach((paramName) => {
if (paramName === 'init') return;
paramName = paramName.replace('_', '');
Object.defineProperty(SwiperContainer.prototype, paramName, {
/ / added configurable:true  HERE to fix crash
get() {
return (this.passedParams || {})[paramName];
},
set(value) {
if (!this.passedParams) this.passedParams = {};
this.passedParams[paramName] = value;
if (!this.initialized) return;
this.updateSwiperOnPropChange(paramName, value);
},
});
});
```
It seems that the property is redefined in a later loop but as it is read only it crashes. Making it configurable fixes this issue.
=> fix: made defineProperty configurable as it broke when minified.

src/modules/hash-navigation/hash-navigation.js
Workaround for issue https://github.com/nolimits4web/swiper/issues/6680. Instead of only checking for a type of `undefined` we also explicitly check for NaN values.
=> Also do an early return on a NaN value

src/shared/process-lazy-preloader.js
Fixes #6724.
The lazyPreloadPrevNext was not working correctly if the loop mode was also enabled.
It also seems that in the part of code for the "rewind" mode, it wasn’t possible to preload slides with an index inferior than the active slide index. Which can happen if initialSlide > 0. It's also the case in the `else` part of the `if(swiper.params.rewind)` condition (src/shared/process-lazy-preloader.js l34), #6684, but I preferred to do a PR for only one issue at a time.
Shouldn’t we just remove that part `(realIndex <= activeIndex || realIndex > slideIndexLastInView)` and just preload the active slide/visible slides?
=> fix(lazyPreloadPrevNext): lazyPreloadPrevNext not working with loop mode #6724

scripts/utils/minify.js
Fixes issue #6863 
This commit addresses an issue with the missing ".min" part in the source map URLs, which leads to broken links for .jsm files. The problem is that the URLs are not correctly formed, causing the files to point to non-existing locations.
In this code change, we have rectified this problem by ensuring that the source map URLs now include the ".min" part. This adjustment ensures that the links to .jsm files are correctly directed to the appropriate URLs, resolving the problem of broken links.
With this fix, the source map URLs will now be accurately generated, and the .jsm files will successfully link to their corresponding source maps, resolving the previously broken links.
=> fix #6863, update scripts/utils/minify.js to fix source maps for ES modules.

src/modules/a11y/a11y.mjs, src/modules/navigation/navigation.mjs, src/modules/pagination/pagination.mjs
N.B. I have not linked this PR to an issue because I can't provide my employer's application as a demo, and it would take vastly more time to strip it down to a working reproduction that I could get permission to share, than it would for the validity of the code fix to be assessed.
Under some circumstances when the the a11y module calls `destroy()` in response to receiving a `destroy` event, it throws an exception (which can't be easily handled due to the asynchronicity).  
When the elements are retrieved from the swiper instance's navigation property:
`let { nextEl, prevEl } = swiper.navigation ? swiper.navigation : {};`
evidently they are arrays containing `undefined`.
The conservative change I have made and which I have validated fixes the problem is to extend the existing truthiness …
=> fix(modules/*): filter out falsy elements

src/types/modules/virtual.d.ts
I made `VirtualOptions` interface generic to be able to specify what is the type of item in `slides` array. By default item type is set to `any` to maintain compatibility.
=> Make VirtualOptions generic

src/modules/scrollbar/scrollbar.less, src/modules/scrollbar/scrollbar.scss
'-ms-touch-action' is not supported by Firefox, Firefox for Android, Safari, Samsung Internet. Add 'touch-action' to support Firefox 52+, Firefox for Android 52+, Safari 13+, Samsung Internet 3.0+.
I discovered issues while using Hint tools to check my website, and some of them were related to Bootstrap so I decided to resolve them in Swiper repository. These changes include properties that allow to support more browsers.
=> add 'touch-action: none' to swiper-scrollbar

src/swiper-element.d.ts
**Before**: Detects custom tags as HTMLElement.
**After**: Detects tags as Swiper's custom element.
https://github.com/nolimits4web/swiper/issues/6466
=> fix(types): detection of custom html tags

src/modules/a11y/a11y.mjs
Similar to #6823 I am noticing intermittent exceptions generated in the `destroy()` method of the `a11y` module, in this case where the `el` argument to the callback passed to `paginationEl.forEach` is `undefined` and so the attempt to `.removeEventListener` is a `TypeError`. As in the previous case, because these exceptions are thrown from within an event handler they are uncatchable and crash the entire page.
It looks like the use of `makeElementsArray`, which filters out such falsy elements (and should otherwise behave identically to the existing code), is also required with the pagination element.
=> fix(modules/a11y): filter out falsy pagination elems

src/components-shared/params-list.mjs, src/core/core.mjs, src/core/defaults.mjs, src/swiper-vue.d.ts, src/types/swiper-options.d.ts, src/vue/swiper.mjs
Our design system team recently ran into some major rendering issues using Swiper internally with some of our LitElement based web components (slotted children slides aren't detected). 
After doing some digging, I stumbled across the change added in #6870 which uses a hard-coded nodeName to ultimately determine if a particular swiper instance is rendering as a web component or not.
This PR should allow continued Swiper usage (as-is) via the `swiper-container` custom element, yet also help other folks with customized web component usage by using this new `swiperElementNodeName` parameter to define the custom element tag name being used in their implementation.
=> Fix: Add Optional `swiperElementNodeName` Prop for (non swiper-element) Web Component Usage

src/types/swiper-options.d.ts
The `SwiperOptions` type definitions, which I believe is used to auto-generate the api website (https://swiperjs.com/swiper-api#param-loopAddBlankSlides), has incorrect information.
The API documentation states that `loopAddBlankSlides` defaults to `false`,  but it actually defaults to `true`. This drove me crazy for some time (my implementation was broken), until I decided to take a look at the source code.
```
src/core/defaults.mjs - line 103
```
https://github.com/nolimits4web/swiper/blob/76355b81e0a7378a10f4e23af36e83f7d9b8ae98/src/core/defaults.mjs#L101-L105
=> fix: loopAddBlankSlides incorrect documentation

src/react/swiper.mjs
React strict mode creates everything two times and destroys one instance again to check for potential leaks in dev move. 
This behaviour causes swiper to potentially handle an already destroyed instance.
=> Fix for React strict mode double initialization errors

src/core/core.mjs
Fixed behavior where the combination of 'initialSlide:0' and 'slidesPerView:auto' would shift the first slide position
- getPropertyValue has an error when getting a decimal point value.
- 'slidesPerView:auto' caused an error in the actual number of slides displayed and the calculated number of slides displayed due to the error.
=> fix: initialSlide #7216

src/core/loop/loopFix.mjs
- Originally observed issue when initialSlide was 0 but reproduced in other cases(#7228 )
- Investigation found activeColIndexWithShift calculation in loopFix.mjs was adding 0.5 when centeredSlides true, causing slidesPrepended to be decimal number in some cases
- Non-integer slidesPrepended value then gets rounded down in snapIndex calculation in slideTo.mjs, causing initial slide index to be less than intended
- Fix by using Math.ceil to round up the slide index variable passed to the slideTo method as argument in loopFix.mjs, ensuring an integer index value is passed to slideTo
=> Fix initial slide index shift with centeredSlides and slidesPerView auto

src/types/modules/mousewheel.d.ts
Declare `enabled` option for the Mousewheel options, to prevent the type check errors.
Currently TS build raise a (non-blocking) error on build:
error TS2353: Object literal may only specify known properties, and 'enabled' does not exist in type 'MousewheelOptions', using the following declaration:
```
<swiper
:mousewheel="{
enabled: true
}"
>
...
```
=> Declare enabled option in mousewheel.d.ts

src/modules/zoom/zoom.mjs, src/types/modules/zoom.d.ts
A numeric `maxRatio` multiplier can be specified as an option on the Zoom module, which is great, however the image can scale past the image's original resolution. This adds a new boolean parameter called `limitToOriginalSize` that will prevent zooming past the image's natural size.
Closes #7303
=> Add ability to constrain max zoom to 100% of original image size

src/types/swiper-options.d.ts
This pull request includes updates to the type annotations in `swiper-options.d.ts` of the Swiper package. The changes are as follows:
1. **effect:** The `| string` part of the type has been removed. This enhances the IntelliSense experience by providing more precise suggestions.
3. **breakpointsBase:** The type for `breakpointsBase` has been updated from `string` to more explicit `'window' | 'container'`.
=> Fix: types of breakpointsBase & effect

src/core/update/updateSlides.mjs
When using centerInsufficientSlides together with slidesOffsetBefore and slidesOffsetAfter, the slides won’t be centered correctly. Apparently slidesOffsetBefore and  slidesOffsetAfter are not taken into account in the calculation of the offset for centerInsufficientSlides.
[Codesandbox](https://codesandbox.io/p/sandbox/swiper-center-insufficient-slides-bug-98rqzr?file=%2Fsrc%2Findex.js)
Resolves https://github.com/nolimits4web/swiper/issues/5436 (was closed already due to lacking information / activity, but issue still remains)
=> fix(core): centerInsuffientSlides takes offsets into account

src/swiper-effect-utils.d.ts, src/types/shared.d.ts, src/types/swiper-class.d.ts
Fixed some wrong types based on source code.
Closes: #7427 , #7205
=> fix(types): fixed SwiperModule, slideTo, effectInit types

src/vue/virtual.mjs
This fix adds one extra logical check in order to avoid pushing more elements to `slidesToRender` that we have slides, i.e. we avoid duplicates. 
Refers to #7557 
Cases with 4+ slides work as before
=> Avoid rendering same slide vnode twice for small amount of slides in loop + virtual mode

src/modules/a11y/a11y.mjs, src/types/modules/a11y.d.ts
Added the 'scrollOnFocus' property with a zero value, which will prevent scrolling to the element that was focused. At the same time, the default value will be 'true', which will avoid backward compatibility issues.
=> added new prop for a11y module - scrollOnFocus

src/core/events/onTouchStart.mjs, src/shared/utils.mjs
Implementation for issue #7623.
I extended the elementsChildren() function in utils.mjs so that it doesn't only check the children of the element, but also assignedElements in case it's a slot.
Please see the original issue for more context.
=> #7623: Added support for using slots as swiper wrappers

src/shared/utils.mjs
The current implementation of elementIsChildOf function references a variable 'element', which is not defined in its scope:
```js
function elementIsChildOf(el, parent) {
const isChild = parent.contains(el);
if (!isChild && parent instanceof HTMLSlotElement) {
const children = [...element.assignedElements()];
return children.includes(el);
}
return isChild;
}
```
I believe it should've been 'parent', the current implementation just throws an error if parent is an HTMLSlotElement.
=> Bugfix: Fixed typo in utils/elementIsChildOf

src/types/swiper-class.d.ts
I only extended the types for the `maxTranslate` and `minTranslate` functions.
=> add types for minTranslate and maxTranslate functions

src/swiper-effect-utils.d.ts
This PR fix two type issues of `swiper-effect-utils.d.ts`.
related: https://github.com/nolimits4web/Swiper/commit/30ce8e0c9c7ce32025275469e9480ca8c81f30a7
> A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './types/index.ts' instead?
In making this correction, I checked that `suffix` parameter is specified at all places in this repo where `createShadow` is called.
> A required parameter cannot follow an optional parameter.
=> fix types of swiper-effect-utils.d.ts

src/modules/zoom/zoom.mjs
Fixes https://github.com/nolimits4web/swiper/issues/7300 
Now, `image.touchesStart.x` and `image.touchesStart.y` are correctly set to `undefined` every time we change the scale to 1.
=> Fix zoomIn after currentScale is set to 1

src/core/update/updateSlides.mjs
Demo here https://jsfiddle.net/pbL17azg/
Try run demo and resize window to breakpoin to 800px or bigger and click to (Slide arrow) to reproduce bug
Added video for visuality bug.
https://github.com/user-attachments/assets/f93246c5-50d9-4bdf-9a98-83300189418d
Bug reproduction if the swiper width bigger then the total width of slides and has option slidesPerView with value 'auto' .
=> centeredSlides with centeredSlidesBounds don't work correct when slidesPerView: 'auto' and width of the swiper bigger then width of slides

src/modules/a11y/a11y.mjs, src/types/modules/a11y.d.ts
To fix accessibility error related to aria-roledescription by adding an additional role parameter to the a11y module.
Fixes #7707
=> Add containerRole parameter to a11y module

src/modules/navigation/navigation.mjs
To be able to have more than one Swiper custom element on a page without having to have different CSS selectors for their custom navigation buttons.
A PR for the issue #7714
=> fix(element): Query the swiper.hostEl for the navigation buttons (#7714)

src/modules/zoom/zoom.mjs
This PR adds a check if Swiper instance has been destroyed before the `allowTouchMove` call in the `setTimeout` callback happens.
Issue: #7722
=> Add sanity check before allowTouchMove call in timeout

src/types/modules/index.d.ts
`Lazy` is no longer exported since [9.0.0](https://github.com/nolimits4web/Swiper/compare/v8.4.7...v9.0.0), 2023-02-01
But it still exists in the d.ts file. This can be confusing.
=> Remove 'Lazy' declaration

src/types/swiper-class.d.ts
The types for `slidesEl`, `slidesGrid`, and `slidesSizesGrid` have been defined, allowing for proper access to these properties in a TypeScript environment.
Issue: https://github.com/nolimits4web/swiper/issues/7767 https://github.com/nolimits4web/swiper/issues/7605
=> Type definitions for `slidesEl`, `slidesGrid`, and `slidesSizesGrid`

src/components-shared/update-swiper.mjs
The same issue we fixed in #7293 is causing #7565.
This patch would handle thumbs inits more gracefully in strict mode.
=> Fix React strict mode double initialization errors for thumbs

src/modules/zoom/zoom.mjs, src/types/modules/zoom.d.ts
This change adds an optional `panOnMouseMove` param to the zoom module to make panning around a zoomed in photo simpler on desktop.
Closes #7306
=> Feat: Add ability to pan around an image on mouse move

src/modules/zoom/zoom.mjs
This fixes an issue in which long pressing a slide's image left the zoom module in a bad state.
Closes #7304
=> Fix: Ensure the Zoom module's  array is cleared onTouchEnd

src/core/breakpoints/setBreakpoint.mjs, src/types/swiper-options.d.ts
Fixes #7816 
Allows specifying a CSS selector for the breakpoints base so that not only the container can be referenced but also elements higher up the DOM tree.
I've tested the solution and it works well. Let me know if the solution looks good or whether any changes are needed.
=> Allow using a CSS selector as breakpointsBase

src/components-shared/get-element-params.mjs, src/core/core.mjs, src/core/events/onTouchEnd.mjs, src/core/events/onTouchMove.mjs, src/core/loop/loopFix.mjs, src/core/slide/slideToLoop.mjs, src/core/update/updateActiveIndex.mjs, src/core/update/updateSlidesClasses.mjs, src/modules/autoplay/autoplay.mjs, src/modules/hash-navigation/hash-navigation.mjs, src/modules/pagination/pagination.mjs, src/modules/thumbs/thumbs.mjs, src/shared/effect-virtual-transition-end.mjs
I love swiper! This project is super fast. I'm using this in a calendar project which has multiple swipers on one page. I'm facing some performance issues on slow mobile phones and I'm trying to figure out ways to help out and make this library even more performant.
I found this previous [similar PR](https://github.com/nolimits4web/swiper/pull/7235) which was not merged. I guess it had too many changes. I tried to keep this small and concise as possible so it's easy to see what changed.
I think swapping [filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) out for [find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) should bring some performance gains and is quite safe thing to do. 
I will …
=> fix: use find where possible instead of filter

.eslintrc.cjs, package.json, src/modules/a11y/a11y.mjs, src/shared/utils.mjs, src/vue/get-children.mjs
A fix for #7761.
I basically had to write my own implementation of the standard `element.contains()` method in `elementIsChildOf` function. This implementation takes into account shadow roots and slots, which are commonly used in web components. The standard implementation does not.
I tested the solution in my own project and it fixes the issue. I have also tested it in the provided demos, it didn't seem to break anything.
Also, I've noticed that .mjs files are not included into the prettier job, so I added them and re-ran it.
=> 7761: Fixed elementIsChildOf returning false for nested web components

src/modules/mousewheel/mousewheel.mjs
There seems to be a typo in Mousewheel module, where it checks for an autoplay param
```js
// Stop autoplay
if (swiper.params.autoplay && swiper.params.autoplayDisableOnInteraction)
```
by which i believe
```js
swiper.params.autoplay.disableOnInteraction
```
is meant.
=> Fix: Typo in autoplay param check

src/shared/utils.mjs
Adds checks for slot support before checking if an element is a `HTMLSlotElement`. This helps prevent crashes in legacy browsers that lack support.
Related to https://github.com/jellyfin/jellyfin-web/issues/5919
=> Add check for slot support

src/copy/package.json
Fixes #7882
The [`src/swiper-vars.scss`](https://github.com/nolimits4web/swiper/blob/master/src/swiper-vars.scss) file is now exported in package.json so that developers using Swiper can override the variables it contains.
=> Export swiper-vars.scss for overwriteability

src/core/loop/loopFix.mjs, src/swiper-element.mjs
If approved, this PR:
- Add a condition to check if the swiper-slide flag `swiperLoopMoveDOM`, avoiding calling the render method again, which was generating the infinite pre-loader injection.
Fixes: #7233
=> fix: remove infinite preloader in loop

src/shared/utils.mjs
This PR will enable projects that are compiled with a version of JavaScript prior to ES2020 to use Swiper V11.2.0 or above.
=> Restore compatibility with ES2019 #7891

src/modules/zoom/zoom.mjs
This PR fixes #7903
- zoom.in function sets an unexpected transform3d value to the .swiper-zoom-container element, if the previous scale value is greater than 1 and the position of the image is not centered.
- The origin of the image should be preserved after zoom.in function is called, as if `transform-origin` was `center`;
CodeSandbox: https://codesandbox.io/p/sandbox/swiper-zoom-forked-w4jlgg
https://github.com/user-attachments/assets/0a1bef43-dfa1-42d3-bd7c-813a087e65ed
This PR fixes the issue.
https://github.com/user-attachments/assets/c0ef4df3-ddfe-4cee-8add-b35a75bdb172
=> fix: fix transform origin of `zoom.in()` function

src/swiper-element.mjs
If approved, this PR:
- Uses swiper state to define the initialization/destroy behavior. Using the state defined in the web component was not reflected, because the `initialize` and `destroy` methods only update the `swiper` instance state.
In the case of `disconnectedCallback`. Only will it be triggered if the component is removed from the DOM.
Fixes: #7666
=> refactor(element): use swiper state for init/destroy tracking

src/core/loop/loopDestroy.mjs
If approved, this PR:
- Checks if `slidesEl` is defined on `loopDestroy`, avoiding cases where components can be unmounted too soon to complete render.
This is a specific case, more information is provided in the related issue.
Fixes: #7881
=> feat: check if slidesEl is defined in loopDestroy

src/types/swiper-class.d.ts
The types for `enabled` have been defined, allowing for proper access to these properties in a TypeScript environment.
Issue: https://github.com/nolimits4web/swiper/issues/7971
=> Type definitions for `enabled` on Swiper

src/vue/swiper.mjs
Added missing `loopAdditionalSlides` and `loopAddBlankSlides` props to Vue `Swiper` component.
They are listed in `swiper-vue.d.ts`  typings, but not in props: https://github.com/nolimits4web/swiper/blob/10084e3c605dad488ff2d517f872d3b23763a581/src/swiper-vue.d.ts#L259-L263
=> fix(vue): added missing props

src/types/swiper-options.d.ts
Fixes #7944
Code completion works properly on the `effect` parameter while allowing an arbitrary `string` value to be passed.
Code completion doesn't work as expected because the resulting type of the effect param is `string | undefined`.
=> fix(types): fix `effect` param type

src/types/modules/effect-coverflow.d.ts
Updated the JSDoc for the `stretch` prop to clarify that it accepts both  
a number (interpreted as pixels) and a percentage string (e.g., `"50%"`).  
This improves readability, helps developers understand the expected values,  
and ensures correct TypeScript type inference, preventing errors when using percentage values.  
Relevant code handling percentage values in `stretch`:
```
let stretch = params.stretch;
// Allow percentage to make a relative stretch for responsive sliders
if (typeof stretch === 'string' && stretch.indexOf('%') !== -1) {
stretch = (parseFloat(params.stretch) / 100) * slideSize;
}
let translateY = isHorizontal ? 0 : stretch * offsetMultiplier;
let translateX = isHorizontal ? stretch * offsetMultiplier : 0;
```
=> fix(types): coverflow effect can be number or string with percentage

src/core/transition/transitionEmit.mjs
slideResetTransitionStart and slideResetTransitionEnd events never trigger b/c the reset event emit is inside a conditional that would never trigger. This moves the reset events to a location that will actually emit.
=> Bug fix for slideResetTransition events

src/modules/keyboard/keyboard.mjs
Fixes an issue where Swiper responds to arrow key presses even when a `contenteditable` element is focused. This prevents users from moving the caret inside editable text.
This PR adds a check to ignore keyboard navigation when a `contenteditable` element is active.
Closes #7665
=> fix: detect contenteditable element in keyboard module

src/core/loop/loopCreate.mjs
This PR fixes #8027 .
The issue is that when the `loop` parameter is `true` and the `slidesPerGroup` parameters are set for multiple breakpoints, unnecessary blank slides are created by resizing the `breakpointsBase`.
=> fix(core): clear blank slides within loopCreate()

src/core/core.mjs, src/core/slide/slideTo.mjs, src/core/slide/slideToClickedSlide.mjs, src/core/update/updateClickedSlide.mjs, src/modules/a11y/a11y.mjs
The `swiper.slideTo()` function does not respect grid.rows settings greater than one. I first noticed this when using keyboard navigation on a two row grid with three slides per view. Once the tabbing gets to the last item in the first row it fails to navigate to the first focused slide on the second row with `fill: 'row'`.
=> fix: slideTo function does not work when grid.rows > 1
